#include "paging.h"
#include "paging_ASM.h"

#define kB 1024
#define MB 1048576
#define KERNEL_ADDR 0x0400000

#define INIT_ADDR 0x0800000

#define PAGE_OFF 0x1000

#define VIDEO 0xB8000
#define NUM_COLS 80
#define NUM_ROWS 25

// PDE low-bit settings
#define PRESENT 0x01
#define PAGE_EXT 0x080
#define RW_ENABLE 0x02
#define USER_ENABLE 0x04

#define MAX_PROCESS 2

// Alligns page directory to 4kB
static unsigned int page_directory1[kB] __attribute__((aligned(4 * kB)));

// Alligns page table to 4kB
static unsigned int page_table1[kB] __attribute__((aligned(4 * kB)));

// static unsigned int process0_pd[kB] __attribute__((aligned(4 * kB)));
// static unsigned int process1_pd[kB] __attribute__((aligned(4 * kB)));

static unsigned char process_mask = 0; // No processes running at boot time


/*
 * initPaging
 *   DESCRIPTION: Initializes paging
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Makes page direcotry and and tables.
 */
void initPaging() {
	unsigned int i;
	process_mask = 0;

	// Reference: http://wiki.osdev.org/Setting_Up_Paging
	for (i = 0; i < kB; i++) {

		/* Sets all pages to not present
		 * Makes them read only and 4kB pages
		 * Accessable only by kernel
		 */
		page_directory1[i] = 0;
	}

	for (i = 0; i < kB; i++) {

		/* Maps to physical memory
		 * Read only, present
		 * Accessable only by kernel
		 */
		// Only enables video memory
		if (i * PAGE_OFF >= VIDEO &&
		        i * PAGE_OFF < VIDEO + ((NUM_ROWS * NUM_COLS) << 1)) {
			page_table1[i] = (i * PAGE_OFF) | PRESENT;
		}
	}
	// NULL Doesn't exist
    page_table1[0] = 0;

	page_directory1[0] = (unsigned int)page_table1 | PRESENT;
	// Maps 4MB page for kernel to 4MB
	page_directory1[1] = KERNEL_ADDR | PRESENT | PAGE_EXT;

	// Loads page directory
	loadPageDirectory(page_directory1);
	// Enables paging
	enablePaging();

}

/*
 * load_process
 *   DESCRIPTION: Called when to change to certain process
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: Process Number
 *   SIDE EFFECTS: Maps memory for process
 */
int32_t load_process() {
	int i, process_id;
	unsigned char mask = 0x01;

	for (i = 0; i < MAX_PROCESS; i++) {
		// Checks for open process
		if ((process_mask & (mask << i)) == 0)
			break;
	}

	if (i >= MAX_PROCESS)
		return -1;
	// Sets process to in use
	process_mask |= (mask << i);

	process_id = i;

	// Below redundant?

	// for (i = 0; i < kB; i++) {
	// 	if (i * PAGE_OFF >= VIDEO &&
	// 	        i * PAGE_OFF < VIDEO + ((NUM_ROWS * NUM_COLS) << 1)) {
	// 		page_table1[i] = (i * PAGE_OFF) | PRESENT;
	// 	}
	// }

	// page_table1[0] = 0;

	// // Enable present bit
	 //page_directory1[0] = (unsigned int)page_table1 | PRESENT;
	// // Addresses starting at 4MB (kernel)
     //page_directory1[1] = KERNEL_ADDR | PRESENT | PAGE_EXT;

	// Addresses starting at 128MB (user program)
	// Base address of 128 MB corresponds to index 128 MB/4 MB = 32
	page_directory1[32] = (INIT_ADDR + (4 * MB) * process_id) | PRESENT | PAGE_EXT | USER_ENABLE | RW_ENABLE ;

	// Flush the TLB
	loadPageDirectory(page_directory1);

	return process_id;
}

/*
:---:--:+yhys+/:::--------://+///::--------------:/+o+oosssssso+::----------------:ohmNNNNmNNNNNNmmdddddddmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNdo:::----------:+yyso/:--/+/:-:+so/::---------------.----://+oyhhhdmNNmmNmNNNNNNNNNNNmmmmNmdmmmmNNNmmmmNmmmNmmmmmdmmmddmNNddmmmmmmmmmmmmmdhdmmmNmmmmmddmmmmmmmNNNmddddmmmmmdmNNNNmmmmmNNNNNNNmmmmmNNNNNNNNNNmhyyyhdmNNNNNNNmmNNNNNMMMMNmmdhsoooooo+++++++++///+syhs+//+sysosdNNmmdhssys+/--::/::------..---.--://oyo/:/osyss/:-------------------------:odNMMMMMMMMMMMNNmNd:
-------:+syo+/::----------:///+//::-------------:/ossoosyyoo+++//:----------.-----:odmNmmNmmmmNNNmmddddddddddmmmmmmmmmmmmmmNNNNNNNNNNNNNd+::///:-------:oyysso/:::-:--:oysss+:--------------.----:+sdmmNNNNNNNmNNNNNNNNmNNNNmmmmmmddmmmmmNNmmmmNmmmmmmmmmmmdmmmmNmddmmmddddmmmdhdmdmmmmmmddmmmdmmdmNNmdmNNmddddmmNmmmmmmmmdmmddmmNNmmmmmmmmmNNNNNNNNNNmddddmmmmmmmmmmmNNNNNNNNmmdhysssssooooooooo+++++oymNNmy+oyhyssyhhhyso//+o+/:+ydyo/----------.---:/:://::/oo///::-------------------------:odNMMMMMMMMMMMNNmNd:
------::/+o+/::-----------://////:-------:/+++//+oyyyssyyyo++++++//////:----------:sdmNmmmmmmmmNNmmdddddddddddmmmmmmmmmmmmmNNNNNNNNNNNNNh/-:/osso/::---:oyyyhs+::----/oyyyyyo/:---------------::+ymmmNNNmdmmNNNNmNNNmmNNNNNNNNNmmmmmmmmNmmmmmddddmmmmmmdddmdhhyhmmmmddmmddddmmmmmmdmmdddmmmmmmmmmddmmdddmmddmdddddmmmmmmmmmNNmddmNNNNmmmmNNNmNNNmmmmmNmmmmmdmNNmddmmNNNNNmmdddmmdhyssssssssssssooooooshdNmhhysoosyhmmmmNmdhs+/::/oymNNds:------------.-------/oo/---:--------------------------:smNMMMMMMMMMMMNNmNd:
--------:/++//:----------::/+++/::-------/+ooo++++++ossyyyso++//////++/:---.-.----:sdmNmmmmmNNNNNmmdddddddddddddmmmmmmmmmmNNNNNNNNNNNNNNh/-::/+shhhyo:-:+yhhyo/::/+++ossssyys+/-----...----::+ydmNNNNNNmmNNNNNNNmmmmmmmNNNmNmmmmmmmmmmmNNmddmmdhhhhdmmmdhhddyyyhdhhdhdhhhdddddddddmmmmmddddmmmmmmmdhhhmmddmmmmdhhdddmmmmdhdmmmdddmmmmmddddmNmmmmmdmmmNNmmmmmmmmmdddmmmdddmddhhdhhhyssssssssssssssssooshmNmyoosyhmNNMMNNMNNNdyo///++oymmho:---------------.--/+/:---.--.------------------------:smMMMMMMMMMMMMNNmNd:
---------::::::----------::/+++/:--------:/+o++/::::://+++//:::://////:--.-...----:sdmmmmmmmmmNNNmdddddddddddddddmmmdddddmNNNNNmNNNNNNNNh/---://+shdds:-:/++/++osyyyyysssyyys+/:------...-+ydmmmNNNNmNNNNNNNNNNNNmmmmmmmmmdmmmmmdddmNmmmNmmmmmmdhhyyhddhhhhhhhhhhhddyysyhdhhdddddddddddmdyhddddddhhhhhhdddmmNmdhhhyhdmdddddyhddhhhdmmmmmhhmmmdmmmmmNmmmmmmNmmmdhhddmmdyyyhhhyyyyyssssssssssssssssssssosdNmdysydNNNNmmdddmmmmdds/:/:/smmho/:-----------------::----.----------------------------:smMMMMMMMMMMMMNmmNd:
--------------------------:::::::---------:///::------:///:-----::/::---....-.----/ymNNmmmmmmNNNNmdddddddddddddddddddddddmNNNNNNNNNNNNNmy/:/+osoooosyys+++oyyhhddhhhhhyyyhyys+/:-------:+ydNNNmmNNmmmmNNNNNNNNmNNNmmmmmmmmdmNNNmmmmmmmmmmmmmmmmmmdddddhhhhyyyyhhhhhyssssyhddhddhhdhhdhyhhhhdhhhdhyyyhhhhhyyddddhhhhddddddddmddhyhddmmmmddddddmmmmNNmmNmmhhmNmmmmmmmmmdhysyyyyyssysssssysssssysssssssssshmNNmddmNNmddhhhhhddmdddyoooydmdy/:::::-----------------------------------------------.-:ymMMMMMMMMMMMMNmmNd:
------------------------------------------------::///////////:--------..--.....---/ymNNmmmmmmmNNNmmdddddddddddddmmdddddddmNNNNNNNNNNNNNmhoosyhddhs+syyyyyyyhhhhhhhhyyyyyyyyso++:---.-/ydNNNNNNNNNNmNNmNmmmmmmmNNNmmddddmmmmmmmmmmdmmmmmmmddddhhdddhyyysyyhyyyhyyhhhysoosyhhyhhhhhhhddhsyhhhdhhhhyyssshhysosyhysyhhhdhyyhhhddmmdhhdyhdmmdhhddmmddmNNmmmNNmdddmmmmmhhdmdhysssssssssssssssssssssssssysssssydNNNNMMNmdddhhhhhhhhyhmNmmmmmmhs//:::::::--------------.-//---.------------------------:ymMMMMMMMMMMMMNmmNh-
------------------------------------------------/+oooo+///++oo+:------...--....-.-/hmmmmmmmmmmmNmmdddddddddddddddddddddddmNNNNNNNNNNNNNmyoosssyyhyyyyyyyyysssyhhdhddhhhhhhhyso/:::+oydNNNNNNNNNNNNNNNmmmmNmmNNmmmmmmmmmmmmmdddmmdhhdmmdmmdhyhyysyysosossssyyyysosysosoooossssssyssyysossyssyyyssssoosssoooosysssssyyhyssyhdyhddhyhhdhhdmmddhhmmmmmdddmmmNNmhhmmmNmdddmddhyssssssssssssssssssssssyssysssyyhdmmmNNmddmdhyyhddhyydNNNNmhyso////::::::----------.---/ss:..----------------.------.-:yNMMMMMMMMMMMMNNmNd:
::::::::----------------------------------------::////++//////:---..--..---...--.-+hmmmmmmmmmmNNmmdddddddddddddddddmmddddmNNNmmNNNNmmNNmo:---:::/+osyhhhhhhhhhhddddddddddhys+/:/shmNNNNNNNNNNNNmmddmmNNNmNNmmmdhhdmmddmmmmdddmmmmhyhddddddysssoooossosyyoossoooossssssssoooooossooooossssooooooooo+oo++++++ooo+oooosssssyhdhhyyhddddhyhhddhyydmmmmdhyyhdNNdyydddmmmmmmNNmhyyyyyysyssssysssssysssssssssssssyhhhhmNmmmdhhhddddhhdmdhhyso++///////:::::-----------/ohh+---.-..---.-------------..-/hNMMMMMMMMMMMMNmmNd:
ddddhhhhhyyyyssssssooo+++++/////::::::------------------------......-......-..--.-+hmNmmmmmmmmNNmmdddddddddddddddddddddddmNNNmmNNNNNNNNmo-........--:///++oooooooossyysso++/:/odNNNNNNNNNNNNNNmddhdmNNmmNmmmmmdhdddddddddmmdddhhdhyyddhhdhysooooooosssssooosssssooosssssooosssoosssssoooooooooooooooooooooooooooooooosssssysssssyyhddyhddhhhhhhydhhyooymNmmmmhdddmNmddmmmmmdhyyyyysssyyyyssssyssssssyyssssssssydmmddmmdmmmhhhhddyooooo++++++/////::::::/ooshho/+syhs++osyo+/:--..------------.-/hNMMMMMMMMMMMNNmmNh:
NNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmdddddhhhhhyyyyyssssoooo++++//////:::::------------:odmNmmmmmmmmNNmddddddddddddddddddddddddmNNNmmNNNNNNNNdo-............------------::::::::/+sdNNNNNNNNNNNNNmmmmdddmmmmmmmmmmmmdmmmdhhhyhdhdhhhyyyysshdysssoooooooossssssssssooooooooooooooooooooooooooooooooooooooooooooooooooooooooossooosssoooossssyyhhyyydhyyhhhhyyhmNmmmNNmdddmmmhhddmmmmdhyyysssyyyyyysyyysssssyyssssssyhhdmmmmNNNNNNmdhhmmdysoooooo++++/////:/syhdNNNMNdsosyhsoydNMNNmmho/--.--------...-+hNMMMMMMMMMMMNNmmNd:
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmdddddddhhhhhhyyyyssydmmmmmmmmmmmNNmddddddddddddddddddddddddmNNNmmNNNNNNNNd+-...................----..---:+oshmNNNNNNNNNNNNNNmmddmmmdmNmmmddddhhhdddhddhhhyyssyhysssyso+ooooososooooooosoooosooooooooooooooooooooooooooooooosssoooooooooooooooooooooooooooooosssssssssssssssyyyyhyyyyyyyyhddhdddmmdhhdmNmddhdmddmmhyyyyyyhhhhhyyyyyyssyyysssssyhdmmmNNNNNNmNNNNmmmmmdysssssoooo+++/+oshmNMMMMMMMNhyhddhshmNMMMMMMNms/--.-----.--.-+hNMMMMMMMMMMMNNmmNd:
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmNNmdddddddhhhhdddddddddddddmNNNmmNmmNNNNNmy+/::::::-------------------/ohmNNNNNNNNNNNNNNmmmNNmmmmmddmNmdhyhhyyyyyhyyyyyyyysosssssooyysooossssooooossoooooooooooooooooossssoosssssoossssooosssyssooooooooooooooooooooooooooooosssssssssssssssssssyyssssyyyyyhdddhmdhhhdmmmmdmmhhmmmddddddddddhhyyyyyyssysssysssyhmmmmNNNNNmmNNNNNmmdhysssssssoooo++ohNNMMMMNNNNNhyyhdmhsshdmNMMMMMMNms:..----..-.-+dNMMMMMMMMMMMNNNNNh-
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNmmmmmNmmmmmmmmmmmmmmmmmmmNNmddddddddddddddddddddddddmNNNmmmmmmmNNNNNmmddddddhhhhhyyyyssssooooshdNNMNNNmmmNNNNmmmddmNNmmdmmdddddyysyhyyyyyyysssssysyssyysosssssooosssossoosssssssssyssssssssssosysoossssossssyysooossssssysoooooooooooooooooooooooooossssssosssssssssssssyyyyssssyyyyhhhhsyydddddmmmddddmmmmmmmddddddddhyyyyssssssyyyyyssydmmdmmNmmmmmmNmmmdhysyyssyssssoooshmNNNNNmmmmmdyoshdds+oyyhddmNNNMMMm+..--.-..-.-+dNMMMMMMMMMMMNNNNNd-
NNNNNmmmmmNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNNNNNNNNmNNNmmmmmmmmmNNmdhhhddddddddddddddddddddmNNNmmmNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNMNNmmmmmNNNmmmmdmmmmdmmmmdmddysyyssyhyyyyssssssssssssssssssoossoosssssssssssyyssssssssosssssssoosysssssssssssssssyooosyyyssoooooooooosssoooossoosssssssoooossssssssssssssssssssssssssyyyhhhdmdmddmmhyhddddmmmdddddddhyyyyyyyyyyyysyyyyyhdddmmmmdmmddmmdhhyysysssysssssyhmNNNmddhhhdddhysyhddyooyhdhhhddmmNNNmo-...---..-+dNMMMMMMMMMMMNNNNNd-
NNNNmmmmmmNmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNmmmmNNNmmmmmmmmmmmmNNNNNNNNNmmmmmmmmmmNNddhhhdddhddddddddddddddddmNNmmmNNNmmmNNNNNNNNNNNNNNNNNNNNNNmNNmNNNNNNNNNNmNNNmmmmNNmmmddddddddddhhhhddhhyyssyyyyysssssssssssssssssooossssyysssyyyssssssssssoossosssoosssssssyysyyyssssyssooosyyyssoooooooooooooooooooooooooossssssooooossssssssssssssssyssssyyyyyyyhhhhdmmdhyhdmmmmdddmmdddhyyyyyyyyyyyyyyysssyyyyhdddhdhhdmdhysyysssssssssshdmNNmddhhyhddyooosyssssso++oyyyyyyhddNNms:..--...-odNMMMMMMMMMMMNNNNNd-
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmdhhhhdddhddddddddddddddddmNNmmmNmmmmNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNmNNNmmNNmmNNNNmmmmdmddddmddhhhhhhysyhysyyyyyssssssssoosssssssssssssssssyyyyyyssyysssyssssosssooosssoosssoossssossysssossyysssooososooossssooossoosooooooooosssssossssssssssssssssssssyyssyyyyyssyyyhhhddyydddhdmmmmmmdhhyyyyyyyyyyyysyyyyyyyssydddmdddmmdhysyysssssssssydmmmdddddhyhmds/+sssoo+ooo:.-+yyyssyhhdmNd+-.--...:omNMMMMMMMMMMMNNNNNh-
dddddddddddddddddddddddddddmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmdhhhhdddhhddddddddddddhddmNNNmNNmmNmmNmmNNNNNNNNNNmNNNNNNNNNNNNNNNNmmmNNNmmdhdmdmmdhddmmmmddhhhhhyyyyssssssssyssssssssssssssssssssyyssyyyyysyyyyysssyysosssoo+ooso+oooooooo+++ossoosyyyyyyssssooooooooooooosssoooosooooooooooooossssssssssssssssssssssssyyyssyysyyyyyyyyyyyyyyhdhhhdmNNNNmhyyyyyyyyyyyyysyysyysssyyhdddddddhyyssyyssssssyysydddhysyhdmdddho/+ssssso++/-.-+yhyyys++oshho-.-....:omNMMMMMMMMMMMNNmNNd-
ddddddddddddddddddddddddhhddhhhhhddddddddddddddddddddddddddddddddddddmmdmmmmmmmmmmmmmmmmmmmmmmmmdhhhhddhhhdhhhhddhhddhhddmNNNmmmmmmmmmmmmmmmmmNmmmNNNNNNNNNNNNNNNNNmmNNNNNmmddddmmmddmddhddhhdddhhyyyyyyyssssssssossssssyyssssssyyyysyyysssooooooooossssssoooooosoooooooooooo+osoooooossossoooooooooooooooooooooooooooooooooooooooooooooosssssssssssssssssssyyyssyyyyyyyyysssyyhhdmmmddmNmdhhyyyyyyyyyyyyyyysyyysyyhhyyyyyyyyysssssyysyssssyhdhyysssyhhdhhs++oyyysso+:--/++oo+/--..-os/----...:smNMMMMMMMMMMMNNNNNd-
ddddhdddddddddddddddddddddddddddddddddddddddddddddhdddddddddddhhhhhhdddhhddddddddhhhhhhhhdddhhdhhhhhhhhhhhhdddddhhhddddddmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmdhdmmmdddhhhhyyyhhyyyssssssssssssoooosyyyyssyyysssssyyyysyssooooooosssosssssssoooossssooooooooosoooooooooooooo+++ooooooooooooossoooossoooooooooooooooooosssssssssossssssssssyyyyyyyyyyyyyyhhyyhhyhdmmdddmmmddhyyyyyyyyyyyyyyyyysyyyhyyyyyssysssssssyysssysssyhdhhhyyssyyyyso++syhhyo/:-:::---.....--/+:-......:smNMMMMMMMMMMMNNmNNd-
ddhhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhyhhhhhddhhhhhdddhhhhhddhddddddddddddddmmdmNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmhddddddhyhhhyyyyyyyysssssssysssssssssssyyyyyyyssssssyysosyhyssssossssssssooooo++++oo+ooo++oooooso+oooooooo++ooooooooooooo+oooooooooooooooooooooooooooooooossooossssssssssssyyyyyyyyyyyyyyyyyhhhhhyhhyhhddmmmmNNNNmmmmmmmmmddddddddhhhhhhhhhyyyyyyyyyyyyyssyssyyhhhhyyssssssssso++oo+//::----....-:////:-.......:ymNMMMMMMMMMMMNNmNNd-
dddhhddddddddddddddddddddhdddhhhhdddddddddddddddddddddddddddddddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhdhhhhddhhhhhhhhdddddmNmmNNNNNNmmNNNmdmmNNNNNNmddmmmmmmmhsyddhyyyyyyyyyysssyyyyhyysssssssyyyyyyyyysossssyysosyyysssyyyyso++ooooooooooooooooooosso++oo++oo+++//+++++++ooooooooooooo+ooosoooooooooooooooooooooooosssoossssssssssssssssysssyyyyyyyyyyhhyhhyyyyyhdddmmNNNNMMMMMMMMMMMMMMMMMMNNNNNNNNNNNmmmmmmmmddddddhhhhhhhhyyyyyyyyysoooo++//:::---.....-:/:--........:yNMMMMMMMMMMMNNmmNNd-
hhhhhhhhhddddddddddhhhdhhhhhhhhhhhhhddddddddhhhhddhhdddddddddhdhhhdddhhhhhhhhhhhhhhhhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddhhhhhhddddmmNNNmmNMNNNNNNNNmNNNmmNMNNNNmmmdmmmddhyhhhyyyyyyyyyysyyyysyyyysssssyyyyyyyyyyssossssyyssosyysosssoooo+oossssssssooo++ossoo+o++++ooosso++++/++++++++++oooooooooooooooooooooooooooooooooooooooooosoossssssssssssssyyyysssyyyyyyyyyyssyyyssyyhhhdmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNmmmmddhhhhysssoo++////:::::-------/hNMMMMMMMMMMMNNNmmNd-
hhhhhhhhdhhhhhhddhhhhhhhhhhhhhddhhhhhdddhhhhhhhhhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddhhhhhhhdddmNNNmNNNMMNNNNNNmmNMNmNNNmmmmmmddddhhddhyyyyyysyyyhyyyhhyyyyyyssyyyyyyyyyyyyhhysyyysssoosssyyssoo++++oooo+++osso++++ooooo+++o+++o++/+++++/////+++++++++++o++oooooooooo+++++ooooooooooooooooooooooooosossssssssssssssysssyyyyyyyyyyysssoossssshdmmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNmmmmmddddhhhhdmNMMMMMMMMMMMNNNNNNd-
hdddhhhhddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdhhhhhhhddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyhhhhhyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddhhhhhhddhhddmmmmNNNNNMNNNNNNNNNNNNNNdmmNNmmmmdmdddhhyysyyyyssyyyhhhyyhhhhssyhhssysyyyssyyyyyysssssooossyyyssso++ooo+//+++o+/+//+oo++oo+o+/+++/::///+oo+////++++++o++++++++++ooo++ooooo++oooooooo+oooosoooooossosoosssssssssssssssyyyyyyyyyyyyyyyyysooosssyhdmmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
hhddhhhhhddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddmmmNNNNMMNNNNNNNNNNNNNNNNNmmdmmmmmdhddddhyyyyyyysssyyyhhyysssyhysyhyssossysossssssssoossooooosoooo+//++/+///+oo+/::/+++////+o+///:////////++++//////++++/++//+++++++++oo++oo++oooooooo+oooossoooooooossssssssssssssssssssssyyyyyyyyyyyyyyssssyyyyhdmmmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyhhhhhhhhhhhhhhhhhhhhhyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddmmNmmmNNNNNmmNmNNNNNmNmNNNmNmdhdmmmNNmdhhyyhyysssssyyyyhhyssssyyyyyyyyysosyyssssoosoooooooooooo++++/+++/+++/+o+++///+++////////::://++////////++////////+++++////++++++++++++ooo++ooooooo++ossssooooosssoossssssssssssssssssssyyyyyyyyyyyysssssosssyhddmNmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyhhhhhhyyhyyyyyyyhhhyyyhhhhyyyhhhhhyyyhhhyyhhyyyyyhhhhhhhhhhhhhhhhdmmmmdmmNNNNNNNNNNNNNmmNNNNNmmmmdddddddmNmddmdyyyssyyyssyyhyyssssyyyssyhyyosssoooooooooooooooooooooo+///+++ooo+oo+:/+++o+//++/:::--://+//://///+++++////////////++++//+++++++++++++++++o++++o+++ooossoooosssoooooosssssyssssssssyysssyyyssyyyyysyyyyyyyyyhdmNmdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
dddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyhhhhhhhhhhhhhhhyyyyyhhyyyyyyhyyyyyyyyyyhyyhyyyhyyyyyyyyyyyhyyyhyyhhyhhhhhhhddmNNmmmmNNNNNmNNNNNNNNNmmmNNNmmmdhdmNmmddmddhhyyyssyyssyyyhhyyyyyyyysssysosssoooooooooo+oo++++oooooo+++++++oso///:::::/:-:://:///::/:::///////////////////++///++++++++++//+ooo+o++++/+++++++++++++oooooosssssssooosssssyssyyssssysssssssssssyyyyyyyysssssyhdmmdmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
NmmmmmmmmmmmmmmmmmmmddddddddddhhhhhhhhhhhhhhhhhhhhhyyyyhyyhhhyyyhhhyyyyyyyhhhyyyyyyyhhhyyyyyyyyyyyyyhhhyyyyyhhhhhhyyyyyyhhyyyhhhhhdmmNNNNNNNmmNmdddmNNmNNNmdmmddmNNmhmmdhdmmmddddhhyysyyyysyyyysssssssoosssoosso++oosssooosoooo+oooo+++++++++ooo+///::///:///:-:::::///::////////////////+//+++++++//++++//++////+++++++++++++ooooooo+ooooooooooossssoossssyssssssssssssssssssssyyyyyyyyysyyyyyhdmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmNNh-
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddhhhhhhhhhhhhhhhhhyyyhhyhhyyyyyyyyyyyhhyyyyyyyyyyyyyyyyyyhyyyyyyyhhdddmNNNNNmNNNmmmmmNmmNNNmmNNmdyyydNNNdmddddmddddhdddhyyyyyssssssssssoossssssssooooooossso+ooooooooo++++oo++//++////+///+/::/+//+/::/++/////:://///++//+///+//+//++/////++++++///++//++++++++++++++++++++oooosssoooossssoosssssssssoossyyssssssssssssyyyyyyyyyyyyhhdmNMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMMMMMNNNmmmNh-
ddmmdddddddddddddddddddddddddddddmmmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddhhhyyyyyhhyyyyyyyyyyyyhhhyyyhyyhyhddmmmmmmmmmNNNNNNNmmddmNNNmmmmddmmmmNmmdhdddddddhyhhhhhyyssyysssssssssssssssssso+osoooo+ooooossoooooo+o++++++++++++////+++++///////++++///+++///++++///++++++++++++++++/++++++++++++++++++++/++++++++++++++ooosssosoossssssssssssssssssssssssssssssssssyyyyyyyyyyyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmNh-
dmmmdddddddddddddddddddddddddddddddddddddddhdddddddddddddddddddddddddddddddddddddddmmmmmmmmmmmdhyyyyyyyyyyyyyyyyyyyhyyhhddddddmmNNNmddNNmNNmmNNmmmmmmmmmhhdmmmNmNNmdmdhhhddddddhdhyyyyyyyyssoosssssssssssssssooooooooosooooo++ooooo+++oo++++++++++++++++///+///++/+///+////////+++o+//////+syyysoo+++++oo+++/+++++++++++++++++++++++ooo++ooooooooossssssssssssssyysosssssssssssssssssssssyyyyyyyhhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNd-
ddddddddddddddddddddddddddddhhddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddmmdhyyyyyyyyyhyyyyyyyyyyyhhdmmmmdmmNNmmmmmNmmmNNmmNNNmmmNNmdhhddhdmmmdddmdhhddhyhhdddhyssyysssssssssssossssssooooosssssoossooooo+osoo+ooooo+++oo+/+oo++++///+++++++++++++++++++++/++++//++oooooooossso+ooo++o++ooo++++++++++++++++++++++oo++oooooooooosssssssssssssssysssssssssssssssssssyysyyyyyyyhhhhdmNNNNNNNNNNMMMMNNMMNMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNmmmmNNNNh-
ddddddddddddddddddddddddddddddddddddddddddddhhhhhhhhhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhdhddmmhyyyyyyyyyyyyyyyyyyyyyyhhdmmddhmmmmmmmmmmNNNNNNNNNNNNmmmddddmmdhhddddhyssyhhdyyyhhhhsssssssssssssssssssosssoossossssssoossosoooso+o+ooooooo++++++o++++++++++++//////++++++o+++//++++ooo++++++++//++oooo+++++//+++++o+++++++++++++++++++++++oo+oooooooooossssssssssssssooosssssoosssssssssssyyyyyyyhhhhhmNNNNNNNNNNNMMMMMMMMNNMNMMMMMNNNNNMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNmNNd-
dddddddddddddddddddddddddhddddhddddddddddddddhhhhhhhhhhhhhddhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddmmhyyyyyyyyyyyyyyyyyyyyhhyhdmmmmdNNNNmmmNNmmmmNNNNmmNNNmmddmNmmmdddddmmdhhhhyhddhyyhhyyssossssssssssoosoosssoooossosssosssssssooooooo+++++oo+++o+++++/+++///+++////++//+////+/++o++oo+ooooooo+ooo+///++ooooooo+++oo++++o+o+++++++++++++++++++++++oooooosoooosssssssssssssooossssssoossssssssssyyyyyyyhhhhdmNNNNNNNNNNNMNNNNNNMNNNNMMMMMMMNNMMNMNNMMMNNNNNNMMNNNNMMMMNNMMNMMMMMMMNNNNNNNNNNNmNmNNmNNNNNNNNNNNNNNNNNNNNNd-
ssssssssooooosssssssyyyyyyyyyhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddmmhyyyyyyyyyyyyyyyyyyyyyyyhdmmmNmmNmNNNNNmmmmmmmmmmdmNNNmddmdmNmhdmmNmhhhdddhhmmdmmddhsssssssssssssoossooososoosssossoossoooooooooooo++++oo+++/++//+///++////+o++++++++++++/++++++++oo+oooooo+oooooooooo++ooooso++o+//////+++++o+++++++++++++++++ooooooooooooosssossssoooosssssssssssssssssssssysssyyyyhhddmNNNNNNNNNNNNNNNNNNNNNNMMMMMNMNNMMNNNNMNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMNNNMNNNNNNNmmmmmmmmmNNNNNNNNNNNNNNNNNNd-
///:://::----::::::::::://////+++///++++++ooooooooooosssssssyyyyyyyyyyhhhhhyhhhhhhhhhhhhddddmdhyysyyyyyyyyyyyyyyyyyyyyydmmNNNNmmNNNNNNNmmmmddmmmmmmmdmNmmmmmddmNmhhdmmNNmdhyhdddhyssssssssssssooooooooooooooosoooossooooooooosooo+++++++++++++++/++++++++++++//++++++oo+++++oooo++++++oooooossssoooooooooso++ooo++++///++++++++++++++++++++++++ooooooooooossssssssssssssssssssssssssysssssssssyyyyyyhhhdmNNNNMNNNMMNNNNMMMMNNNMMMNNNMNNMMNNNMMNNNNNNNMMNNNNMMMNNNMMNNMMMMNNMMNNNNNNNNNNNmmmmmmmmmmmmmmmmNNNNNmNNNNd-
///:::::-------------::::::::://::-----------------------::::::::///+++++++++osydddhhhhhdddmmdyyyyyyyyysssyyyyyyyyyyyyhddmmNNNNNNNNNmmmmNNNddmmmmmmmddmNdhdddmmmhdmmddddddhyhhhhyyyssossssssooooooooooooossoooooooosoooooooo+++ooo+++++++++++++++++++//++++/++/+o++oooooo++o++++++++o++++oooooooooooooooosoooosoossooo++++o+++++++++++++++++++++o+ooooooossssssooossssssssoossssssssssysssssssssyyyyhhhdmNNNMNNNMMMNMMMMNNNNNNNNNNNNNMMNNNNNNNMMMMMMMMMMMNMMMNNNNMMMNNMMMMNNNNNNNNNNNNNNmmmmmmmmmmmmmmmNNNmmmmmNNNd-
://:::::-----------::::://////////::::-----------------------------:::--------/shddhhhhhhddmmdysssyssyssssyyyyyyyyyyyydddmmNNNNNNmmNNmmmNNNmddddddmmddmmdddhhddyyddhhyyyhdhyyhhhhhysoooosssoooooooosooooooooooossoooooo++ooo+oo+oo+++/++++++/+++///+++++//+++++oo++/+oo+++++oo+++o++++++++++oooooooooooooooooo+ooooossso+oooo+++++++++++++++++++++oooooooooooossssossosssssssssssssssyyyyyysyyssyyyyhhhddmNNMNNNNMNNNNNNNMMNMMMMMMNNNMMNNMMMNMMNNNNNMMNNNNNNNNNNNMMMMMMMMNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmNNNmmmmNNNh-
::--::::-------:::::::://///++////////:::--------------------------:::--------:shdddhhhhhddmmdyssssssyyyssyyyyyyyyyyyydmmmmNNNmmmmmNmmmNNNNmddmhyhmmddmmhhhhhddhdddddsyddhyyyyyhhyssossssoooooooooooooossooooooooooooo+++oooooooo++++++++++++++/++++o++++++++/++//////+++++++//++++++++++++++ooosoooooooooooooooo++++oo++++++++++++++++++++++++++++++ooooooooooooooossssoosysssssssyyyyyyyyyyyyyyyyyyhhhdmmNNMMMMMMMMMNMMMMNNNNNNMMNNNNMNNNNNNNNNNNNNNNNNNNNNMMNNNMMMMMMMMNNNNNMMNNNNNNNmmmmmmmmmmmmmmmmNNNNmmNNNNd-
-----------::::/::::://////++++++//////:::------------------------::::--.---.-/shddddddddddmmhyssssssssssyyyysssssyyyhdNNNNNmmmNNNNNmmmNmmmmNNmmdhdmdhhmmdddmdddhyhhyyddysyyyyyyyysssssssoooooooossoooooooooooo++ooo+++oo+ooo++oo+++/++/++/+++++++//+/+++/+++///+++++++++/+////++/++++++++++ooooo+oooooooooooooooooo++++++++++oo+++++++++++++++++++++++ooooooooooooosssssssysssssssyyyyyyyyyyyssyyyyyyyhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMNNNNNNNNNNNNNNMMNNNNNNNNNNMMNNNMMMNNNNNNNNNNmmmmmmmmmmmmNNNmmmNNNNNh-
----------://////::////++++////++////:::::::---------------.------:::::-----.-/sdddddddddddmmhsssssssssssssyyysssssyyhmNNNmNmdddmmdmNmddddmmmmmmddmmmdhdNmhdmmdhyyhyyddhhyssysssyyssoooosoooooooooooooo+++oo+ooooo++++ooooooo++ooo+++++++++++++++/////++++/++++++//+///++////+/////////////+++ooo++ooooo++oooooo++oo++o+oooooo++o+++++++++++++++++++oooooooooooooooossssssssssssssssyyyyyyyyyyysyyyyyyyhhdmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNh-
----------:////////++++++++++++////////////::------------------.--:://::----.-/ydddddddddhdmmhssssssssssssssssssyyyydmNNNmdmmddmNdhdNNNmmmmmmdmmdmNmmdhdmNmmddddhhyshdhssysyyyhyssssssooooooooooooo++o++oo++ooo++++++oooooooo++o++oo++++++++++//+++/////++///+++//+++///////++++/////+///++//+/////+///+++oooooo++//+oo++++++o++ooo++++++++++++++ooooooooooooooosssoossssssssssssssssyyyyyyyyyyyyyyyyyhhhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNd-
-------:://////+++++++++++++++++///+++++++//::-------------------::///::---..-/yddddddhhdddmmhsssssssssssssssssssyhhmmNNmmNNmmmNNmmNNNNNNmddhhmdmmdddddmddmdhhydhyydddhyyyyyyyyyyssssoooooooooo++++++++oo+++++++++o+ooooo++o+++++++o++oo+++++++++++/++++ooo++o++++++//++//++//++//////////////////////+++o++o+ooooo++oooo+++++++ooooo+++oo+++++++++oooooooooooooosooossssssssssyyyyyyyyyyyyyyyyyyyyyyyhhhddmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNNNh-
------::/++++++++++++++++/++++++//+++oo++/////:-----------------::////::---.--+ydddhhhhhhddmdyssssssssssssssssssyyhdmmdmmmmmNmmmNmddmmdddhyyddmdddddmmdddhddhyhdhyyhhyyyhhysssooooooooooooooo++++o++++oso++++oo++oo+oo+o++/+++++++++++oo++++oo+++++++++ooo+++oooo++///++//+++///+++////////////////////++++++++++ooo+++++oooo++++ooooo++++++++oooooo+++oooooosooossssssssssssssyyyyyyyyyyhhhhyyyyyyyyyyhhhddmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNd-
------://++++++++++++o++//++++++++++ooo+///++//:---------------:://////:-----:+ydddhhhhhhhdmdysssssssssssssssssyyydmNNmmNNmmNNmdhhhdhyyhddhdmdmmmdhddhhyysydyhhhyysssyyyssssyssoooo++ooo+oooo+++++++oos+:/++oo++ooo+o++++++oooooo+oooooso++oooooo++++ooo+++++oo//+++/++////++//+++/:://////:://////////////+++++++++++++++++++//+++ooooo++++++o+++++oooooooosssooooossssssssssssssyyyyyyyyyhhhyyyyyyyyhhhhdddmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNh-
-----::/++++++++/+++++++++++++++++++++++////++/::------------::////////:::---:ohdddhhhhhhhdddyssssssssssssssssssyhdmmNNmNNNNmddddhhhhhmmmmmmhhdddhhddhhmmdyssssssssssyhhhysssooosooosoo++oooo+++++oo++oo+++++o++++oooo++++ooooo++++ossooooooosssooooosooooo+osoo+++//+o+///++//++//::::::////////////////////////+++++/////+++++++++++oo++++++++o++oooooooooosssssoossossooosossysssyyyyyyyyyyhyyyyyyhhhhhhddmmmNNNNNNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNh-
-----:////++++////+++++++++++//+++++++++////////::----------::::////////:::--:ohddhhhhhhhhdmdyssssssssssssssssssyyddmmNNNNNmdhsshddmmmmmddmmhhhdhyyyhhyydhysyyyysssosssyhhysoossoooyhs+ooooo+++++oooooo+++++o+o+oo+++++oooooossssooosysosssosysoooooossoo+++oyso+++++++++++++////////::::////::::::::::::://///////++++++///+++/////++ooo++++++++oo+ooo++oooooooooooooooooooooossssssssyyyyyyyyyyhyyyhhhhhdddddmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNd-
----://////+++++/++++++++++++++++++//////++/////::--------:::::::/:://////:::/ohddhhhhhhhhddhysssooossssssossssshdmmmmNNNNdhddyhmmNNmdhhddyyhhyhhyssyyysssyhhshhyhhssoosoooo+ooooooshyo++oo++++o+oo+++++++++o+++oo+oo+ossoooo+oyysoosyysssssyhyssyyhyhhsossssyys+//+ooo+++oo+//++/////:::::::::::::::::::///:://///////++/////+///+++++oo++++++++++ooooooo+o++ooooooooooooooooooossssssssyyyyyyyyhhhhhhhhhdhhdddmmdhddddddddddddddddddddddddmmmdmmmdmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmddhdmNMMMMMMMMMMMMNNNNNNNh-
---::/++///++++++++++++++++++++++////////++////::--------://::::/::::::::::::/shdhhhhhhhhhddhsssoooooosssooosyyydmNNNNNNmmmdmddmNmmmNmmdhysysosddysyyssssoyddhdhyyhsooooooooooo+++oyhy+++o++oooo+oo++++o++++++++++oooossoooossssssssyyysooossyysshdhyyyyhyooooo++oossooooooo+////////////:::::::///:::::::::/:::::///////////+++//++++++++++++oo++++++++ooooooooooooooooooooooooossssssssssyyyyyyhhhhhhhhhddhddddmddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddmmmdddmmmmmmmmmmmmmmmdhys+ohNNMMMMMMMMMMNNNNNNNNh-
--:::/++++/++++++++++++//+++++++++++++////////:::--------:/::::/::::::--:::::/sdddhhhhhhhdddhsoooooooooooooosyhmNmmNNNNNNmdddmdhddddmmmdysyhhyhddhhhhssyhyyhhssyyyyssoooooooooooooohhyo++++ooooso+oooooo+++osoooosssosssossssysssyssshddhyo+osyyyhysssssosssyhyyyysosssyyyysoo++++/////////:::::::::--::////::::::/:://////:/:://////++++++++++++++//++++++++o+oooooooooo+++oooosssssoosssssyyyyyhhhhhhhhhhhhdddddmddhhhhhhhhhhhhhhhhhhhhhhhhhhyyhhhhhhhyyhhhhhhhdddhhhhhhhhhhhhhhhhhhhyyso+sdNMMMMMMMMMMMNNNNNNNNh-
---:://////+++++++++//++//++++++++++++///////:::---------:::-:::::::---:://::+ydddhhhhhhhdddhsooooosooossooosyhmNmmNNmmmNNmdhhhdysydhsosyhhdhyhhmmdddyhyydhhhhyyssyssooooooo+++oooshhyo+++oooooo+++ooooo+ossso+ossysoosssssssyysssssyhddddhso++++++osshhyhhyyyyyssyhyyyhdhhyssyhhhyysso//:::::::::----:---:::::--:::::::::://::://///+//+++++++++++//++++++++o++ooo+++++++++ooo++oossoosssssyyyyyyhhhhhhhhhhhhddddmmmdddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhhhhhhhhdddhhhhhhhhhhhhhhhhhhhhyssoosdNMMMMMMMMMMMNNNNNNNNh-
----:://///////++++///++////+++++++++///////:::------------------::::::///:::+ydddhhhhhhhdddysooooosooooossooshmNNNMNNNNNmmdddddysyhyyyyyhdmNmssddhhhysssydhyhhyossoooooooooooooooyhhyo++o+ooooooo+oo++++oso++sysooooossooooossooshyyhhhdhyysossooo+//++sysyyyyyyhhysyyssyyyhhyssyhyhyssyso++//////:--:::---::----::::::::-:::::::///////+//////++++////++++++o+++++++++oo+++oooo++ooooossssyssyyyyyyhhhhhhhhhhhddmmmdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdhhhhhhhdddhhhhhhhhhhhhhhhhhhhhhyysssymNMMMMMMMMMMMNNNNNNNNh-
-----:::///+++++++++++++/////++++o++///::/::::--------------------:-:::::::-:+yhdddhhhhhhdddysoooooooooooosooshmNmdmdddmmmmmdmmdysoshdhyyhmNdhdyshdmmhsssshhhyssyysooossooooooooosyhhyo++oooooooooooo+o+ossoosyyyysooossooo++osssshdhyooys++oo+oyyhhhyo+++/+yhyyyssyysyhhysyhhyyhhhhhhhyyssyhhysooso+///:---//:---:/:--::::::::::::::////////++//+++/:///++++//++++++++//////+++++oooooosssssssyyyyyyhhhhhhhhhhhdddmmdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhhhhddddhhhhhhhhhhhhhhhhhhdhhhhyysyhmNMMMMMMMMMMMNNNNNNNNh-
------::://++++++++++++++++++++++++//////:::-----------------:::::::::::----:+yhdhhhhhhhhdddyssooooooooooosoosydNNmmdddmmNmhdmNNdsohdmdyyymNmdddsydmdhhyysooyyyysssoosssooooooosooyhhhso+oooooooooooooooossssssssyysosooo++++shyo+sssyyo//+++ooyyoosooyyso+//oys//oooyysoosyyyyssysyso+syyyyhhyhhysyyysyy+::/o+/:-:/:-------::-:::::::////:::://///++//::://///++++++++///++///++++ooooossssssssyyyyyyhhhhhhhhhhhhhdmmddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdhhhhdddddhhhhhhhhhhhhhhhhhhhhhhhhyhdNMMMMMMMMMMMMNNNNNNNNh-
--------:::/++++++++++++/++++++++///////:::------------------:::://::::::::-:oydhhhhhhhhhddhyoooooooooooooososdNmmmmdmmmdmdsshdmmhhhhmmhhyhdmmmmNNdhhhhyyyyyosyysoossoosoossssooosyhhho+ooooooooooooooooosysosyssysooooooooooyso/+ss++oo++oo++++o++ss+//+oo+/:/+++///+o+///ossso+o+osyyssyyyyyyyyhhhhhhhhyo++osy+://::-..--------:::-:://:::::///////:.-:---:://////++/////+////++++++oooosssssyyyyyyyyyhhhdhhhhhdddmmmdhhhhhhhhhhhhhhhhhhhhhhdddhhhhhdddhhdddmmmdddddddhhhhhhhhdhhhhhhhhhhhmNMMMMMMMMMMMMNNNNNNNNd-
:------::::/++++++++//////++++/////////:::-------------------:::://::::::::-:ohddhhhhhhhhddhsoooooooooooooosshmmmddmmmdmmdddddddmmmdmmdyyyydddhyyyyhyyhyssysoyyyssssosssoossoooooshhhhsooooooossoooooooosyysyysssssso++ooso++oo++osoo+//o++++/////:////::::::::://:::///::///+/::/+oosyyyyyhysoyss+shoohhhs++syyoos+:--..----------::-:::::-:::://///:----..--::::::////://///////++++++oooossssyyyyyyyhhhhdhhhhhdddddddhhhhhhhhhhhhhhhhhhhhhhhddddddddmddhdmmNNNmddmmddhhhhhhhhhhhhhhhhhhhdmNMMMMMMMMMMMMNNNNNNNNd-
::--------:::///////////++//////::::::::----------------------:::///::::::--:ohdhhhhhhhhhddhsooooooooooooooshmmmNmmmmmmmmdhyydmmdddddmmdyydmhhddhhhhyydhhhyyyyyyyysossssssssooossyhyhyso+oyyysooooossooossyhs++oossoooooo++ooo+//++//++////////:-:/:::--:::-::::::::---::-:::::::://+++o+::+syoyssosy//hhso//os++ooo:----::-..----::::-:---:::::////::::--...-:---:::::::::::///////+++++++oooossyyyyyyyyhhhhhhhhhhhddmddhhhhhhhhhhhhhhhhhhhhhhhdddddmmNNmmmNNMMNmddddmmdhhdddhddddhhhhhhddmNMMMMMMMMMMMMMNNmNNNNNh-
:::---------::://///++++++///:::::::-------------------------:::://::::::::-:ohdhhhhhhhhhddhsooooooooooooooyhmmNNNdhdmmmmhysyhhddhhdmmddhyhdddmhhhhhysyssyyyssyssssssssssssoossssyhyhysooyhdho+oosssoooooydh+:+ssos+oso++++oo+/////+/::://///:::::::::...---...-..---------------:--:+++:://++/+oooss/osooo+oso+oss+--:://:-.---..---------::::://+/:::--..`..------::::::::::////////+//+++oooosssyysyhhhhhhhhhhhhhddmmddddhhhhhhhhhhhhhhhhhhhhhhhhdmNNNNNNNMMMNmmmmmmmdddmmNNNmmdhhddhhddmNMMMMMMMMMMMMMNNmNNNNNh-
/:::::--------:::::::///////::::::-------------------------:::::::::::///::-/shddhhhhhhhhddhsooooo+ooooooooydmNNmmddddhdmmdhhddddhyhhddddhhhyhdyyyyhdssssyyyysysosssssssssooosssyhhhdhyyyyyhy+++ooooooosyddo:/+ooos+os+/++/+o+///::://://:///:/:------........-..--------------:--..-:/:-::::::/+o+sy//+so+oss++ss+/+//:::-----.-------------:::////:---...``...-----:::::::::////////++++++oooosoossssyyhhhhhhhhhddhddddddhddhhhhhhhhhhhhddhhhhhhhhdmNNMNMMMMMNmdddddmmmmNmmmmmmdhhhhhhhddmNMMMMMMMMMMMMMNNmNNNNNh-
::::------------------:::::::--------------------------------::::::::/::::--/shdhhhhhhhhhddysooooo++ooooooshmNNmmmddddhdmmdddmmdhhyhyhddddddhddyhdhhdhyyyyssysssssssssssssooosssyhhhhhyyyyhhs++++ooossyyhhhssso/+oo/+o//+/::/++/:::/:://:///:::/:---------......----:-::::::::::---:---::::::-::++/++:/os+/oo+/+o+oo+::++:....--......------:-::////:----.....-------::::::::////://++ooooooo+ooossssssssyhhhhhhhdddhdmmddhdddhhhdddddddddddhhhhhdddmmmNNMMMMNNNmdhddmmmmmmmmmmmddhhdhhhhddNNMMMMMMMMMMMMNNNNmNNNNd-
:::------------------------------::::::------------------------:::::::------/yddhhhhhhhhhddyoo++oooo+oooooshmmmmmmmdmmddddhhdmmdhyyddddhhmmdysyhhhhhdyyyyyssyssssyyysssssssossssyhhyyyyyyyyyo++++ooosshdhhhdmy++sso+///////:////////:///://///::::::::---...-------::::::/::////:/:/:::::::--::::///::/+++++/////+++++/:-------.``....--------://:/::::---...----::::::::://////++//ossyyyyyyssoosssssyysssydddhhhdddddmmdddddhhhhhddddddddddddddmmmNNNNNNMMMNNNNmmmmmmmmmmmmmmmddhhhhhhhdmNMMMMMMMMMMMMMNNNNNNNNNh-
----------:---------------------::////:---------------------------:--------:+yhdhhhhhhhhhdhyoo+++++++++ooosdmmmdddmmmddhhdhyyhdmdsoydmdddmmdhhyhyyhdhysyyyyssyyyyyyysssysssssssyhhyyyyyyyyyyo+++oooosydhyyyhho+++o++////////////++/////////:///:://:::------.----:/::////////++//++/////////:////::::///:::/:--//++///::://:-.```````..----::://///+/:::------:::::///////+++/+oo++oyhdddmddmmddhhddhddhhyyyhhdddddhddmmmddhhddhhhhhhhhhhhdddmmmNNNNMMMMMMNNNNNNNNNNNmmmNNNNNNmmdddhhdhhhdmNMMMMMMMMMMMMMNNNNmNNNNh-
::::-----------------------------://+//:--::::::---------------------------:+yhhhhhhhhhhhdhso++++++++++oooymNNNNddmmmdhhdddddddmhysyddddhyhhdmmddhhhhhyyyyyssyyyyyyysyyssssssssyhhyyyyyyyyhyooo+ooooshhyyyhho++//+/+++///////++++++/++++++/////////::::-----:--::://///////+++++++++oo+++++++++/////::::::::::////::////:-...```````.....---::/:::////:/:::::://::/++syyssyysoss+/:/syhhhhdmmNNNNmmNNmmmmdhhhhhhddddhddmmmdhhdhhhhhhhhhhhhhhhddddmNNMMMMMNNNNNNNmmNNNNNMMNNNmmmdddhhhdddddmNMMMMMMMMMMMMMNNNNNNNmNh-
:::::::::------------------------::////:--::///:--------::::::::::---------:+yhhhhhhhhhhhdhso++++++++++oosymNNNNdhddddddddddhyhddddmddddhhhyhmdhddhyhhyyyyyyyyyyyyyyyyyysssssssyhysyyyyyyyhyoooooooshhyyyhhs//+++//////+++++o++++++++o++++//++++/:::---..`.....----::://////++++++ooooooooo+o++++////////:::::::::::--:-..``..``````...----:::::::////:://////////os+oyhysssyyys++//:/+oydddddmmNNNmmNmmmmdmmmdhdmmmmmmmmmdddddhhhhhhhhhhhhhhdhhhhddmNNNNNNNNNmNmmmmNNNNMNNmmddddhhhhhdhhdmNMMMMMMMMMMMMMNNNmNNNNNh-
///////:::::---------------------::////:--::///:-----::://::::::-----------:+yddhhhhhhhhddhs+++++++++++++ohmNNNmddmdddmmmdhhhhyyhhhmmmmdhyyhhddhddhhhhyyyyyyyyyyyyyyyysyyssssssyhyyyyyyyyyysoosoooshhysyyhh+/++++/++++++oooooo++++o+++++++++////::--.`````....-::--::::://://////+++oooooooooo++++///+////:::::------.......```````.--.-----::::////////////////++ososyhysssooyhhyo++//osyssyhhdmmNmmmmmmmmmmmmmddmmmmmmmmmdddddddhhddhhhdhhhhhhhhddmmNNNNmNNmmNNmmNNNNNNNmddddddhhdddddddmNMMMMMMMMMMMMMNNNNNNNNNh-
//////////::::--------------:::////////::-:::::::::---::/::::::::----------:oyhhhhhhhhhhddho+++++++++++++oymNNNmdmNNmddmddddmmdyhddddddddhhhhddddhyhhhyyyyyyyyyyyysyyyssssssssyhhyyhhyyyyyys++ooosyhyssshhs/++++++++++ooossooooooooo+++++///::::::://+++ooooosssssssssoossosooo+++//++oooooooooo++++///////:/::::::--.........`````...-----::::///+++++////++++++++ooosyo+++/oyysosoooooooooooosyhhdmmmmmmmmmmmmmmmmmmmmmmmdddhdddhdddhhhhhhhhhhhhddmmNNNNmNNNNNNmmNNNNNNmmddhhdddddddddddmNMMMMMMMMMMMMMNNNNNNNNNd-
///////////:::-------------::/+++++////:::::::-:::::--://::::::::::--------:oyhhhhhhhhhhddyo+++++++++++++shNNNNNmmmmmmmmdyhhhhdddmdydmdddhhhddddhhhhhhyyyyyyyyyyysssyysssssssshhhyyhhyyysyyo+ooooyhhsyyshy+:/+++++++oooosssooooooooo++++/:////+oossssssooosssssssssoossssssssssssssssoo++oooooooo+++++++++//:::---.....``...```````...-::::::////++++++++++o+++++++++++o+++//++++ooooo+oooosssssssyhhhdmmmmddmmmmmmmmmmmmmmddddhhhhddddddhhhdddddddmNNNNNNNNNNNNNNNNNNNNmmddddddddddddddddmNMMMMMMMMMMMMMNNNNNNNNNd-
////////////::::----------::/+++/////::---://:::::::-::/::::///////:-------/oyhhhhhhhhhhhdyo+++++++++++/+ymNmNNNNNmmdmddmmdhhhhdmmhoydhhhhhddddhhhhhhyyyyyyhhhyyysssyssyyyyssydmhssyhyyyyhsoossooyhhhysyhsos+:/+++ooososssoooooooo+++++++++oossssooo+//+/:-------:/+/+oooossssssssssyyyyso+oooooooo+////+//:::--..`...`...`````````..---::::://///+++++++oo++++++++/+//////////++++++oo//++oo+++osssysssyyhhhhhhmmmmmmmmdddddddddddddddddddddddddmmNNNNNNNNNNNNNNNNNNNmmdddhhddddddddddddmmNMMMMMMMMMMMMMNNNNNNNNNd-
///////////////:::----::-::/+oo+/////::---::::::::::::/::::://///++/:------/ohhhhhhhhhyhhhyo+/+////++///ohmmdmNNNmmmddmmmdddmdhhdddhhdmdhhddhhhyhddhhyyyyyhhhhyyysssssssssssyyhhssshyyyyyhssyhyo++syhsyyyssy+-:/++ossssssosooooooo++++oosyyssoooo+//:----...-::::::+oooo+/++/+osoossyyyyyyyo+oooooo+++++////::-.`....``...````````..----:::///+++++++++++oo++++++++/+/////+//////:///////////+++++//+++/+ooosssyhddddmmdddddddddddddddddhhdddddddddmmmNNNNNNNNNNNNNNmmdddddddddddddddddddmmMMMMMMMMMMMMMMNNNNNNNNNh-
/////:::///////::---:://:::://++///:::::::::////:---:////+/+////////:::::::+shhhhhhhhhhhdhs++//////+++++oydmmmmmmmdddmmdhyydmdhhdmmhhhddhhdmdddyhhyyyhyyyyhhyyyyyyyyysssssyyyysssyyhyyyyyhhyddyo+oyhysssssss:-/++oooooosooooooooo+oooossysssooo++o++ooooosyyhhyhdhhddddhdhhyssooo+ossssyyyyyysooooo++++++///:-...`....```..``````...-:::::///++++++oo++ooooo++++++++++//////////////////://///+///////+//++/++ooosyhddmdddddddddddddhhddddddddddddddddddmmmmmmmNNNmmmmdddddddddddddddddddmNMMMMMMMMMMMMMMNNNNNNNNNh-
o+++/////::///::---::////::::::////::::://////+:.` `.://////+++////::://///oydhhhhhhhyhhdhs++///////++/+ohmmmmmmmddmmmmmdddmhsshdmmdhhyyhhhddhdddhyyyhhhhyhyyysyyyssssssyssyyyyssyhhyyyyyyyyyhyoosyysssssss+-/oooossssssssoo++oooooossssssssssssssyydddmmmNNNNmNNNNNNNmmmmmddddddhhhysossyyyhhysoooo+++++///-.`.........-..```````.--::::///+++o+++ooooooooo++++++++////////////:///////////+++++++++++++//++++ossyyyyyhddddmdddddddddddddddddddddddddddddddddmmNNmmmddddddddddddddddddddmNMMMMMMMMMMMMMMNNNNNNNNNd-
ssyssso+//::/:::::::://////::-://+//::/::://///:`   `-/////////:::::://:::/oyhhhhhhhhyhhdhs+////////////sdmmmmmmmdmNmmmmdyhmdyyddhhdhhdhhhdmdhhddhhhhhhhhyhhyyyyyyssssyysssyysssshdhyyyyyyysyhs+osyssssooss/-/+++osssssssoooooooosssyyyyyyyyyyhdmmmNNNNNNNNmNNNNNmdmmmmdhys/:/ohddddmdhssssssyhysoooo+++////-.....--------........-:::::////++oooooooooooooo+++++++//////::::--::://///://///++++++++o++++++++++oosysyhddhddmmddddddddddhhdddddddddddddhddddddddmmdddddddddddddddddddhdddmNMMMMMMMMMMMMMMNNNNNNNNNd-
yyyyyyyo+/::::::::----::///::::////::::::::::::.`   `:///////::-:::::::::-:+yhhhhhhhhhhhdhs+////////////sdmmdmdmmmNmdmmmhyddhhhdddddhhdddhddmdhhhhhhhhhhhhhhyyyyyysssyyyssyyyyyyyhdhyyyyyyyyyhsoyysssoo+oso::/+oo+oooossssssssssssyyhhhddhhdNNNNNmmNNNNmmmddddhhdyyh::ydhs/.` ``.:/oshdddhysoosyyso+++++////:.`..----::----....-..-::://////++ooooosssssoooo++++++///:------:---::::://///////++++++ooooooo+oo+++osssyyyyhdmmmmdddddddddhdddddddddhhddddddddddddddddddddddddddddddddddddmmNMMMMMMMMMMMMMMNNNNNNNNNd-
ossysyys+/:::::::------::::::::://:::::--:::---.```.-///++///::::::::------+yhhhhhhhhhyhdyo+///////////+shmNNmmdmNNmmmmdyyddhhddmmhhhhdddhhhhhhhhhhhhhhhhhyhhyyyysssyyyyysssyyyyhdhysyyyyyyyhdyshyys+o++so:..:://+ooosyyysossssyyhhhddmNNNNNNNNmyyhmmmmddddddmdhddddyyhdhs/.```` ```.-:ohmdhysssyyso+//////:-```.-:::::--:---------::///////++ooooossssooooo+++++//:------------:::::::::///////++++++ooooooooooooooosssydmmNNmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmNMMMMMMMMMMMMMMNNNNNNNNNd-
++osssss+/::::::::----:::::::/:://:::::::::---..--::://///////::-----------+yhhhhhhhhhhhdyo/////////////ohNNNmdddmmdhdmhoyddhyddhdhddhddhhhhhhddhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyhddyyhhyyyyysyhyosyyooo/os/-.`.:-:++sssyysyyo+oyyyhdddmNNNNNNNNmh+:-/shddddddddddddmmdddhy+-````````....-/shddhyso+oso+/:::-....--:////::::::::-::::::::////++ooososssssssooooo++//:----------------::/::://///////+o++oooosoossssoooosssyhhdmmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmNMMMMMMMMMMMMMMNNNNNNNNNd-
:/+ossso+/:::::::----::::::::///::::::::::::-----::::://:///::::-----------+yhhhhhhhhyyhhso///:////////++ymNNNmddddddmmhhdhhdddhddddmdddddhhhhddhhhhhhhhhyyhhyyyyyyyyyyyyyyyyyyhdmdhddyyyyyyyyyossoo++ooo/-``...:::yyyyysssy+oys+ohmmmNNNNmdddhhyo/:/oyhhdhhdmmddmmddhys/.`..`````......-:oyhhhhys++so:.````.--://////:/:::::--::////////+++++ossssssyyysoooo++//::---...---://++ooosssssssooo++///++++ooososssssssosssyyyyydmddddddddddddddddddddddddddddddhdddddddhdddddddddddddddddddmmNMMMMMMMMMMMMMMNNNNNNNNNd-
///oooso/:::::::------::::::////::------:::::----:::::/:::::::::---.------:oyhhhhhhyyhhhhs+/:://:://///+oymNNNmmmNmmmmddhhhmmhhhhhddddhdddhhhhhhhhhhhhhhhhhhhhhyysyyyyyyyyyhhyyhddyyyhdyssssssssssoo++o+:://++oosyysyys++sssosyyssyyyyyhhssssssyyyyssyyyyyyssyyhhhhhyy+-`  ```````.....-:+oosoosyhyo++o-``.-:://++/+////////::://////++/++++ooosssssyyyyysoo+++/:-----::/ooo+++osoo+oooooosossssssso++++++oosssssssssssyyhhhmmmmmdddddddddddddddddddddddddddddhdddhdddmmddddddddddddddddmmNMMMMMMMMMMMMMMNNNNNNNNNd-
ooooo++++/::://:::--:::::::///:::--------:::::-----::::::::::::---......--:oyhhhhhhyhhhdhs+///::::://::/ohmmmNNNNNmmmmdddhdhdddmdddhhhhhddhhdddhhhhhhhhhyhhhhyyhyssyyyyhhyyyyyyhhyssyddyyysshhsysooooss+:/+++ossyysosssyysssssssssoooooooossssoosyo+osyssys:`.:syyso/:.`       ````..--/osyyssooosyyo/+so+//+++++++++++/////////+++//++/+++++ooossssyyyyyysoo++/::::/+++o+/:---.`...-:/::/o+oosssssssssoo++oooossssssyyssyhdmNNNmmmdddddddddddddddddddddddddddhdddddmmddddddddddddddddddmNNMMMMMMMMMMMMMMNNNNNNNNNd-
yssssooooo+///::--:--:::::::::::-...----------------:::::::::::--.......--:oyhhhhhhhyyhdho//:::::://:/::odNNNNmNNNNNmmmmdmhosdddddddhddddhhhddhhhdddhhhhhhhdhhhhhyhhhyhhyhhhyysyyyysyddyyysyhhyyssoooyo+++ssssssssssssssoooo+osoo++++///+++///+++++//osyysoo+++oyys+///:----:///+ossyyyhhhhhyyyyhhyyyo++ssoooooooo+++++//+///////////++++++++ooosssssyyyyysoo+///+++/:---:/+oooosssoooo++oo+//+ooossssyyyyso++oosssyyyssyyhdmNNmmmmmmdddddddddddddddddddddmdddddddddmmddddddddddddddddddmNNMMMMMMMMMMMMMMNNNNNNNNNd-
oossssssss+/::--------::::-:::::--..-----------------::::::::---.........-:shhhyhhhhyyhdho//://::::::::/odmNmmNNNMNmmmmNmddhhyhhhhmmdddhhhhhddhdddhhhhhddhhhdhhhhyyhhyyyyhhhyyyyyyysydhysyyhdmdysyyhhhsssssssssssssssossooo+++oo/:/++/::/::--:--::--:+ss++o+os+oyyyyysyhhysyhyhhyyyyyyssssooooosssssoooosssssoooooooo+++++++++//////++++++++++oossssyyyhhysso+++o+//+syyhhhddhhysyddddddddddhhhysoooooosyyyyysooossssysyyhhdmmmddmmNmddddddddddhdddddddddmmmddddddddddddddddddddddddddddmNNMMMMMMMMMMMMMMNNNNNNNNNh-
//++ooooo+/:----------------:--:----------------------::::::--...........-/shhhyhhhhyyhdho/:::::::://:::+ymNNNNmNNmmdhhdddhyshdhhddhhdhhdhhddddddhhdhhhhhhhhhhhhhhhhyyyyhhhyyyyyysyyhddyssyhddhsyyo+osyhhhhyyssssssssssssssooooo++++/://::---:-.-----::..-/++/:+s+/o+//+ooooo++oo+++++ooossssssso+/+ooossssssooooooooo+++++++///////+++++++++oooooossyyyhhysoossoosys+/+yddddhhhddddddddddddddmmmdhhyssssssyyhyoooossyysyyhdmmmmmmNNNmdddddddddddddddddddmmmdddddmmddddddddddddmmmddmdddmNMMMMMMMMMMMMMMMNNNNNNNNNd-
:://++o+++//:------..---------------.----.....---::::-----::---..........-/shhhhyhhhhyhdyo/::::::::://:/+ymNmmmNNmdddhhhhdhdhhhyhdmdddhhdhhhddhhhhdddhhhhhhhdhyyhhhhhhyyyyyyyyyyysyyhmdyyhyssoo+++oooooosydhyoosssssssoooooooooo++++///:-...``````.--:/:--//-...-:-:::--::////++osssssssoosssoooo+//+oosoosssssssoooo+++/////:///////++++++++++ooosssssyhdhyssyyo/:-.`-ohyyhdddddddhhdddddhho:-/shdmhhddhyyysyhhssosyyyyyhdmNNmmmmmmmmdddddddddddddmmmmmmmmmmdddmmmddddddddddmmmmddddddmmNNMMMMMMMMMMMMMMNNNNNNNNNd-
///+ooooo++++/:---------------------..---.....----:::---------...........-/shhhhhyhhhyhdy+/:::::::::/:::/shmNNNNNmddddhhhyyhhhyhdmmdhhhddhhhddddhhddddddhhhhhhyhhhyyhhyyhyyssyyyyyyhhddds/--:+osossoooooooohmdsoooooooooooooooooo+oooosoo+++++++/++/++++/:+s+/+oossosoooosssyssssssoooooooooooooo+++oooossssssoooo+++++///////////////+++++++++ooosssssyyhdhysyhs:.``.:oysshhhdo--/yhs+yhhhhy+.``./shmmmmdddhhhhhyssssyhhhhdmNNmmmmmmddddddddddddmmmmmmmmmmmmmmmmNmmdddddddddddddddddddmmNMMMMMMMMMMMMMMNNNNNNNNNNd-
///++++++++++/:--------:-----------------.....----::-------..............-/yhhhhhhhhyyhdy+/::::::::::/+osyhddddddddddddddddhhhhhhddddddmdddhhmddddddddddhhddhhhhyhyyyyyyyysyyyyyyyyydms/-:/+++ooosoooossooooydysoo++++++++++ooo++oooooooooosyysosssssssso+osooooosoossssoooossosssooooooooooooooooooooossssssooooo++++/////:////:://///++++++ooo++oossssyyhddhy/-.` ``-+yhhdhs+-../hdo:shhdhyo-.````-+ydmmmmddhhhhysssyhhhdmNNmmmmmmddddddddddddmNNNNNNNNmmmNmmNNNmdddddmmmmmddddddddddmmNMMMMMMMMMMMMMMNNNNNNNNNNd-
::::://::::::::---------------------------....------------...............-+yhhhhhyhhhyhdy+::::::::/+syyhyyyyyyyssyyysyyhhhhddddhhhhdmmdddddhdddddddddddhhdddhyhyyhyyyyyyyyyyyyyyyyhdh+.:+soossooosoooosoosssshdho+++++++++/+++++++++ooosooosssoossssoooosso+/+ossooososssssooooooooooooooooooo+oooooooooooooooooo+++//////////::://////////+++++++oossssyyyhddho+//:-.:+shhhhhyhddddhddhdddhs/.`..```.:shmmmdddhhdhyyysyhhdmmmmmmdddddddddddddddmNNNNNNNNNmmmmmNNNmmmmmmmmmddddddddddddmmNMMMMMMMMMMMMMMNNNNNNNNNNd-
-----:-----::--------------------------------------------................-+yhhhhhyhhhhhhs/::::::/oyyyysyysyssssssssoossssssyhddddhhhddmddhdddddddddddddhhddhhyhhhhyyyyyyyyysyyyyyhds--+ooooooossssssoossossssyhdhs++++++++++++++++/+++++o++oso++oss++o++oooo+++ossooo+/+osssoooooooooooooo+++ooo++++++++ooooooo+++////////:::///::::///////+++++oooooossyyyyhmdhhsoosyhhhddhyooyhhhhhdhhdhhy+-```````..:ohmmmmmmdddhhyyyhhdmNmmddddddddddddddddddmmNmmNNNNNNmmmNNNNmmmmmmmmddddddddddddmmNMMMMMMMMMMMMMMNNNNNNNNNNd-
-------------------------------------------------------.................-:+yhhhhhyhyyhhhs/:::::oyhysoosssssysssssoooooooooosyhdddhhddhddddddhddddddddddhhhhhhhhyyyyyyyyyyhyssyyyhdy--+ooosooosssoossooossssssyyhdhs+++++++////+++//++++osooooo+++oooo+::/++o+//+so+/++:://ossoo+++++oo+++++++++++++++oooooo++++++/////////:::://////////////+++++ooooosssyyyyhdhyy+-..:osyyho/sdhhhhhhhhhys/..``````..-:/shmmmmmmmddddhddmmmmNNmmdmddddddddddddddddddmmNMMMNNNNMNNNNmmNNNNNmddddmmdddddmmNMMMMMMMMMMMMMMNNNNNNNNNNd-
-----:------------...----------------------......------.................-:oyhhhyyyyyyhhho/:::+syyso+osssssossssssooo++++++ossyhhdhhhddddmdddddmddddddddhhhhyhhhyyyyyysyyyysssyyydh-./+osssosooooooooooosssssyhhddmh+/++/+////+++++++o++///++++//:::+oo+++++osysossso++++/+oso+oooo+++++//////+++//++++ooooo+++////////::/:::::://///////+//+++++++ooooossyyyyhddhyss+:----:/osyyhhhhhhhyo:.````````..-:/+oshdmmmdmddddhddmmmmmmmmddddddddddddddddmmddmmNNNMMMMMMNNNmmmNNNNNmmmmmmmmddddmNNMMMMMMMMMMMMMMNNNNNNNNNNd-
::::::::-----------------:--------------...``  ``............``........--:oyhhyyyyyyyhhho/::/ssoooossooo++++oooossso+////+ooossyyhhhhhddddddddddddddddhhhhhyhhhyyyyysyhysyyssyyhd+`:++ososooooooooooooossssyyyhdddho+////////+++ooooooooooooooo+////++///++ooso+++oooo++o+osoooooo++////////////////++++++++////////:::::://:::://///////+++++++++ooooossyyyyyhddyssso+//::--://osyyyhhhyso++/:::--:/+osyyyyhdmmmddddddddddmmmmmddddddddddddddmmmmmmNNNNNNMMMMNNNNNNNmmNNNNNNmmmdddddddmNNMMMMMMMMMMMMMMNNNNNNNNNNd-
------------------------------------.......      `......````````........-:ohhhyyyhhhyhdy+::+ssoooooo+++++++++++++osso++//+++ooossyyhhhddddddddmdddddddhhhhhyhhyyyyhyyyyyyyyssssdh-`/++oooooooooooooooosssssysshhhhhyhyo+/////++++++oooooooooooso+++ossooosso++++++++o++ossooo+++++/+////////////////++//++++/////::///:/::::::://///++///++++++++ooooosssyyyyhhhdhysssoo+/////::://++ossyhhhhhhhhyyhhhhhhhhhhhdmmmmmdddddmmdddddddddddddddmmmNNNNmmmNNNNMMMMMMNNNNNNmmNNmmNNmddddddmmddmNNMMMMMMMMMMMMMMNNNNNNNNNNd-
-------------------------------...........`       ``...`````````........-:shhhyyyhhhyhdy+/+oo/++oo+////++++++++++++osso//++++ooossyyhhddddddddddddddddhhhhhhhhhyyhhyyyysyyyyssydy../+++++ooooo+++++++oossssyyyyhhy/-//ss+/+//++++//++++so+++ooooo++osssoossoooosossso++oo+ooo+///////////////////////++++++///////::::://///://///++++++++++++++ooooooosssyyyhhhhdhyysoo++o++//+++/////+ossyyhyhhhyhhdhhhyyyhddmdddddmmdddddddddddddddddddmNNNNNNmmmmNNNNNMMMMMMMNmmmNNNmmmmmddddddddddmNNMMMMMMMMMMMMMNNNNNNNNNNNd-
-----------.............``..-...........``         `````````````........-/oyhhhyhhyhyhds+oo+//+oo//::////+++++++////+ssoo+++++oosssyyhdddddddddddddddhhhhhhhhyhhhhyyyyyyssssssyds.-/+++++ooooo++++++++oosyyyyhhyo///-`:o////::/+o+++++++/////+so+++ossso+osoosssysssso++//++///:::::::////////////++++++////////////::::/::///+++++//////++++++++++oooosssyyhhhyhddhyysso+++oo++++oooo+++++oososyyssyyyyssyyhddddddddhyhddddddddddddddddddmNNNNNNNNNmmNNNNNNMMMMNNNNNmNNmmmmmdddddddmddmNMMMMMMMMMMMMMMMNNNNNNNNNNd-
------................`````..``````````            `````````````````....-/shhhhyhhyyyhhyoo+:-/++/:--:://++++++++////:/osso+++oooossyhdddddddddddddddhhhhhyyyyyyyyyyyyyyysssssshdo.:+/+++oooo++++++++oossyyyysso++/:--/+oosyso++++o+++/:::///:/oso+/+oooo+osysossssoo+++//////::::/:////:://////////////////////::////////////++++++////+++++++++++++oooosssyyhhhhhdhyssssoo+++++oo+++oossooooooossssssssssssyyhddddhhhhhhhhhddddddddddddddmmNNNNNNNNNNNNNNNNNNMMNNNNmmmmmmmmddddddddmddmNMMMMMMMMMMMMMMMNNNNNNNNNNd-
::::----------.............```````````              ``..````````````....-/shhhhyhyhyhhhyo/--:++/-----:/+++++++++////:::+ssooooooossyhdddddddmddddddhhhhyyyyhhyyyyyyysssssssssshd+.:+++++++++++++ooooosssyso++++::+s+/+/++//+osoo+/+++/::///o+/+oo+/+ooossoooo+oso++osso+////::::::::://///////////////////////:::://///////+++++++++++++++++++++++++++oossyyyyhhddhhhyssooooo////+++o+++ooosssooooooooooooossyyhhhhysyhddhhhhdddddddddddddddmNNNNNNNNNNNNNNNNNNNNNNNNNmmmmdddddddddddmmmNMMMMMMMMMMMMMMNNNNNNNNNNNd-
yyyyysssssoooooo++++++++///::--.......```           `....````...........-+shhhhhhyyyyhys/--:++/-----://+++++++++////:://osssoooossyyhdddddddddddhdhhhhhyyhhhhyyhhyysssssssssssydo.:+/////+/+++++ooooooooo+/++/:.-/:..---:-.``.-/+o++++++/+++ooo+o++++++ooooooo+ooo+osss+////:::::::::://////////////////////:::::////////++++++++++++++++++++++++++++oooossssyyhdddhhyssooooooo+///+++++oo+oooosssooooooooossssyyyyyyyyhhddhhddddddddddddddddmNNNNNNNNNNNNNNNNNNNNNNNNmmdddddddddddddmmmNMMMMMMMMMMMMMMNNNNNNNNNNNd-
ddddddddddddddddhhhdhhhhhhhhhyssssssoo+/:-.`    `..-:///////////////////+shhhhhyyyyyyyo/:-:+o/:-----//++++++++++//////++osssoooosyyhddddddddddddhhhhhhyyyhhhyyyyyyyssssssssoosyds--//+///++++++++++++++++//so/:+/-.....://:::.`.-..-/+//////://++++ooosooooo+o++++ooosoo//::::::::::///://///////////////:::::://///++++++++++++++++++++++++++++++++++ooooooossyhhdddhyssooooooo++//++++++++oo++oo+oooosssssssssyyyyysyyhddhhddddddddddddddddmmmNNNNNNNNmNNNNNNNNNNNNmdddddddddddddddmmmNMMMMMMMMMMMMMMMNNNNNNNNNNd-
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhyso++ssyyyyhhhhhhhhhhhhhhhhhhyhhdhhhyhyyyyys+:-:+++:----:/+++oooooo++++++++oosssssoooosyyhhdddddddddhhhhhhhhyyyyyhhyyyyysssssossssssydhso+++//+++++++++//+++o+-.:so+:/:---:::///:---.--```.+ys/////////////+++++++++++++////++/:::::::::::::::///:///////////::::::::://///+++++++++oo++++++++++++++oo++++++oooooooossyyhdmdhysoooo++oooo++++++++ooooooo+o++ooosssssyyyyhyyyyhhhdddddddmmddddddddddddmmmmNNNNNNNNNNNNNNNNNmddddddddddddmmmmmmmNMMMMMMMMMMMMMMMNNNNNNNNNNd-
hhhhhhhhhhhhhhhhhhhdhhhhhhhhhhhhhhhhhyhhhyyhhhhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyhyyso/-:/+/:-..-:/+++oooooooo++oooosssso/::+ooosyyyhhddddddddhhhhhhyyyhyyhyyyyyyyssssoosssoosddsssssso+++oo++++++++/::../o/::::::::/::::-----.---::--+ys+:::::::::///////////:::::::::::::::::::::////////:://::://::::::::::://///+++++++++++++++++++++++++++++++++++++oooooossyyyhdmdhsoooo+++++++++++++oo+++++oooo++oooooossyyyyyyyyhhdddddddddddddddddddddddmmNNNNNNNNNNNNNNNNNmdddddddddmmmmmmmmmmNMMMMMMMMMMMMMMMNNNNNNNNNNd-
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhyyso+:-/++/-.``-:/+oooooooooooosooosso+:-.-+ssssyyhhddddddddhyhhyyyyhhhyyyyyyyyysssssooossssydy+oo+/+//+oo/-:+//:://:/oo+/:::::::::::--.-:---:::://+//ohyo/:::::::::::::/:::///::::::::::::::::::://::::::::////::::-------:://///++++++++++++++++++++++/+++++++++++++++++oooooossyyhdmmdysooo+++++oooo+oossooooooo+ooooooooooossssyyssyhhddddddddddddddddddddddmmmmmmNNNNmmNmmdddmmddddddddmmmmmmmmmmNNMMMMMMMMMMMMMMNNNNNNNNNNNd-
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyhhyyhhhsso/-:+o/:.`..:+++ooooossssossooo+++/:--:+ossssyyhhdddhhhhhhyhhhyhhhhhhyyyyyyyssssssoooosssyds/:-./y/..-../ss:.:ossyy/:::--::-::::::---:::::/++++//+osyyho:-:::::::/::::::::/::://::::::--::-::::::::::::::::::----------:::////++++oooooooooo+++//////////+++++////+++++++oo++ossyyyydmdhsoo++++++ooooossssssosssoooooooooooosssssyyyyyhddddddddddddddddddddddddddddmmmmmddddddddddddddddmmmmmNmmmmmNNMMMMMMMMMMMMMMMMNNNNNNNNNh-
ddddddddhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyhhyyyyyso+::/o+/-...-/+oooososssosoooo+/::--::+ossoossyhhhddddhhhhhhdhhhhhhhhhhyyyyyyysssssssssssyhdhs+/oyyyyoosso+oyyso++y+``::---:::::::--:::::-://:--::/+sooyy/-:::::::::::::::::::::::::::-:::-:::::::::::::::-------..----:::://+ooosssssoooo++++++////////://////////////++++++++++osssydmmdso++++++++oooosssssssosssssoossssssosoossyyssyhddddmmdddddddddddddddddddddddddddddddddddddddmmmmmmmmmmmmmmNNMMMMMMMMMMMMMMMNNNNNNNNNNd-
yyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhhhyyso/-:+o+:.`.:/+ooosssssssooo++/:-..-:/+oo+/+ossyhhhdddddhhhhhdhyhhhhyyyyyyhhyyssssssssoosydh+-+yys+//ooo+//++/::/+yy:`.-:---:/:::/:::::://--:-.--://++++/+oo+:::::::::::::::::::::::::---::::::::::::::::-------......-://++osssssssssooooooo+++++/////::::/::///////////////+++++oooosyhmmdyo++++++++osssssssssooosssyyyyyyssssssssssyyyhhdddmmmddddddddddddddddddddddddddddddddddddmmmNmmddmmmmmmmmNNMMMMMMMMMMMMMMMNNNNNNNNNNh-
+++++++++++++++++++++++++++++++oo+++++++++++++oooooooooooossssssssssssyyyyyyyhhhyys+:-:+o+:-.-/++oosssssoooo++/:----://+++/:/ssosyhhyhhyyhhhhhdhhyyyyyyyyyyhhyssyyssssssooyhy-`:++++//++++///o++/++oyy-`-:---:/:::::::---.------::/+++++/:---/syo////::::::::::::::::----:--::::::::--::::------.....--:/+oossyyssssssoooooooooo+++/////::::::::::////:::::////////++oooosshmmmhoo+++++++osssyyyyyssoooosssssssyyssossssssyyhddddmmddmmddddddddddddddddddddddddddddddddddmmdddddddddmmmNNMMMMMMMMMMMMMMMMNNNNNNNNNd-
++++++++++++++++///////////////////::::::::::::::::--------::::::::::::::::::////+o+:-:+o+:--:++ossssssooo+/::-..--:::////:/oo+oyhhhhddhyhhhdddhhhhyyyyyyyyhyssyysssossssyhs-.:o+++++/++++//+++++oosys-`.-----:::::-::--:----://+yss+:-:-..-``/y+////:::::::--::::::::------::::::::::------......`.-:/osssyssssssssoooooooooo+++++////:::::--::-::::::::::::////////+oooosyhmmdyo++++++++osssssssyysooooooossyyysssooossssyhhdmmNmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddddddddddddmmmmNNMMMMMMMMMMMMMMMMMNNNNNNNNd-
+++++++++++++//////////////////::///::::::::::::::-------------------------------:++/::+so///++ossyyssoo+//:-.....--::///:/ooo+oyyyhddddddhhdhhhhhhhhhhyyyyyysyssssssososdd.`/o+++//++++/++++//+ooooyy:`---:---::-:::::::-:::+//++/::-------``-o/::::://:::::::::---::--------:::::--::------......-/ossssssssoooooooooooooo++///+/////::::-------:::::::::-::::://////+oossydmmdyo+++/+++++ooooossso+oooooosyyyssssssssssyyhhdNNMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNMMMMMMMMMMMMMMMMMMNNNNNNNNh-
++++++++++++///+++////////////////::::::::::::::::-------------------------------:++/::+oo+++ooosyyysoo+/:--.``...-:::/::/oso++osyhhddddhhhhhhhhhhhhhdhhhhyyyysssssssossyho`:++o+//+++++//++/+oo++syhh/`.::--:::---::::::/:///:::....:+:.-::---//:::-----::::-::------::-----::-------------..--.-/+osssoooooooo+++++++++++++++/////////::--...--::::::-::::::::::::::///+ossydmmdyo+++++++++osssssysyysooossssyysosssssssyyhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNh-
++++++++///+++///++/////////////:::::::::::::::::---------------------------------+o+///ooo++oosyyssoo+/:--.....---::::::+oooo++syhhhhddhhhdhhhhhhhhhhhhhhysyysysssssosshy-./++///++++++++++++++ossyyy+``::--:::--::::::://+/:/:-.```-:-..:+:` .:/::-----.--:--:-::----------:::---------------::/osssssooo+++++/+++//////++//+////::::::-.-......--------:::::::::://////+ossyhdmdyo++++++++++ooossssyyssosyyyyyysossssssssyydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNh-
+++++++//////////////////////::::::::::::::::::-----------------------------------/o+///+oo++osyyssoo+/:-.......--::::::/oo+++++shhhhhddhhddhyyhhhhhhhhhhhysyyyssssssosyyo.:+++++++++++++++++++oosyyyhs. .:::::-::://+/:/:-.``-/:`./+:-:/+/:-.-/+/------------:::::--------------:--:----------/+sssoooo+++/////::::::://///////:::--.....```   ``.....-------::::::///////++osyhdmdyo++++++++++++++++ossssssyyysssososssyysyyhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNh-
++++++++++//////////////////::::::::::::::::::::------------------:---------------:+o+//+osooosysssso+/:----..---::::--:+so++++oshhhhddddddhhhhhhyyyhhhhhhhyyyssssssoosyy+.:///+++++++++++++oo+osyysyyhyso/:--+o+//+//:-:+o:+/////:-.:+o/-:++:---:--.-----------------..---------::-::--:-----/ossoooooo++///::/:--:::::::-:::-----``````         ````..`...----::::/:////+++oosyyhddhy++/++++/+/////++++ooosssssoosssossssyyyhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
+++++++++///////////////////:::::::::::::::::::::--------------::---------------::-+oo///ossosssssoo+/::-----:::::::--.-/ss+/++oyhhhhhhddddhhhhhhyyyyhhhhhhyyyyssssssosyho-////++/++++++++++oooooosssyo-./ooo//+:-:--.`.`:y+o++o/--:/:-:/++/:-...------:-----::-----..---::----:---:::--::---/ooooooooo++//:::::::-----.....```````              `````..`...--::::::/:://///+oosyyyyhddys+//++////////+++++ooooooooosoossssyyhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNd-
++++++++++////////////////////:::::::::::::::::::---::::-------:::::::::---::::--::/ss++/+ssossssooo++/::::::::://:::--.-+soo++oyhhhdhhhddhhyyyyyyyyyyhhyhyyyyyysssssoosyo.///////+++o++++++++oyysyhs/:-`/+-```-.`-+///:::/-+/:+///:-:++:/-`:s/.-------:----:::-----------------::-::::::--:/ossooooo+++//::--::-....```  ``    `` `````..````````.......-----:::::::::::///++ooosssyyhdds+/++//////////++++o+oooo+oooossssyyhhdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
oooo++o+++++++++++++++++////////////:::::::::::::-::-:::-----:::::::::::::-::::---::oso+/+osssssssoo++//::::::://///::---/osssoosyhhhhhhhhhyssyhyyyyyyyhyhhyyyyyssssssooyy/////://++++++++++osssyyso/-../shy/:oooo//:/+/+o:::-://-.-:::---..:/:::--.--.------:::---:---.----.----::::::::--:/oooo++++////::--...```` `````````..........---........-------::::://::::::://///+o++oosssshddy+////////////++++o++oooo+oooosssyyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNd-
oooooooooooooooo+ooooo++++++++++++/////////:::::::::::::----:::::::::::::------:::::+sso+++syyssssso+//:::::://///////:://osssssyhhhhhhdhhhysyyyyyhhyyyyyyyyyyyssssoosssydhyo++oso++++o+oooossoo+:/o/:/soosssoo/++//+/::::::::///:-----.----..-/++:--::::---:------------------:::::::::::::+ssoo++////:::--...........-------::::::::::::::-----:----::::::::://:///////////++++++ooosyhdds+////////////+++++++ooo++oooossyhhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNd-
sssssooooooooooooooooooooo+++++++++++////////:::::::-::::---:::::::::::::::-:::::::::oyso++osssssssso+/////////////////++ooo++osyhhhhhhhhhhhyyyyyyyyyyyysyyyyyssssssooshho/yyssyso+oo+ooo+++/:::..+yssso-/o++///:::::::-:/:::++++:.--...:/::---://///++::--:-----::------------::::::::::::/+sso+++////::---------:-:::::::::://///////////::::::::::::::::::://:://////////++++/++++oooyddyo/////////////+++++oo++oooooossyhhhhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNd-
hhhhhhyhhhyyyyyyyyyyyssssssssoooooooooo++++////:::::::::::-::::::::::::::::::::::/:::+ssoo+oosssssss+//://///+//++++++++ooo+//osyhdhhhhhhhhhyyyyyyhhyyyyyyyyyyssysossssyho:+oooooooooo/---/oyo//syo++//://////:::::-:/so/:/++/:::..-:.`.-:-------::--:/++/--::::----:-------::::::::::://///+sso++/////:::::::::::::///+++oooo++++++++++////////::::::/:::::::////////////+++++++++++++oshdhs////////+////+++++ooo++oooooosyhhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNd-
dddddddddddddddddddddddhhhhhhhhhhhhhhhyyyyysssssoo++oo+++++++//+++////////////////////syssooosyssssso+///++++++++oooosoooo++//oyyhhhhdhhhhhyyyyyyyyyyyyyyyyysssssssssssyhy:+o++/-:/-:ooossysso+oo/://::-/////:-///++/:+s+---/+:----.--...:/-.--::://::-.-://:-:::::-------:--:::///////::://+oso++++////:::::///+ossyyhddddyyyso+++++++++//////::::::://:/:////////++/+++++o+//++++++++oshhhs+/:////////++++++++++++ooooosyyhhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
dhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhddddddddhhdddddddhhhhhhhhhhhhhhhyyyyyyyyyyyysyssssssss+oyyooo+ossssyysooooooooo+++++oosssysoo+osyyyyhhhhhhhhhyyyyyyyyysssyyyysssssssssooshy/::/oysoosyyyssyysssssyy+///:://+so/:::/yy/:://:--:+/.-::..-..-:..-::-..-:------/oo+/::-:-::--:::::::://:://:::///+oooo+++/////////+ossyyhhhyyyyysssoo+++////+++++////////////////+++++++++++++ooo+++++++++++osyhhs///////////+++++++++++ooooossyyhhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
ddddddddddhhhhhhhhhhhdddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhdyo+oyooo+osssssyssssssso+//:::-:://+osyhyhyyyyhhdhhhhhhhyyhyyyyyssyyysyysssssoosssosyhdhdddhhhhhyyyyyhy+/+++os+/:::/ssooo+--::+yo--::::-.+/--//::--:/:..-:-```---:---..--:/+o/::::-----:::::://///////++++oosoo++/////++ooooooooooo+++ooooo++///:::::+oo+//////////+++++/++++++++ooooosooooo++++++++oyhyo/:::////////+++o++++ooooooosyyyhhhhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
dddddddddddddddddhhdddddddhhhhhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyysssyhdyo/+sssooossyyyyssssssso+//::-...--:/+syyysyhhhhdhhhhhhhhyyyyyssssyyysysssssooosssoosooshdhhdyyyso+++hy/:/oyhyss+:/+oys:::::::/os/--:::::::////:--//----....-.``.-.-/:-:://:+oo/:::::::::://///////////+++++ooooo+++++++//:--:://///////++//////:...-/++////////++++++++++++++oooosssssssssoo++++++oshhs/:::://///////+++++++++ooosssyyyyhhhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNh-
ddddddddddddddhhhhdddddddddddddddhhhdddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyhhyo//+sssooossyyssssosss+/://:-....-:/+syyysyhhhhhyhhhhhhyyyyhhyssyyysssssssooosssoosoooohy//hdhsoo+++shysoo++++oo+/++ss/::::/::os//::///::/:.:::-----:::::-.--....`....--:+//+oo+/::::::::////////+////++++++oooooo++++/-.......--://////////////-..-://////++++ooooooooo+osyhhhsossooo+++++++///+osyyo+::::::////////++++++++++ossssyyyyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
dddddddddddddddddddhhdddhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhhdy+/:/sysoooossssssssso+/::/::-....-:/oyssssyhyyyhyyhddhhhyysyhyyyyhyssssssssssssoossssssyy:.+hdhsyo://yhs//::/+oo////+o/::////++/://://::::/+s/:-.-.-``.--:---..```......``.-/+oso///:::::::////////+++++++++++++++++++/:--::-::::::::////:::::///:-.--/++oosoooooooosysssyhhhhdhsoo+//::::://+/+osyy+/:::::::////////+/++++++++oosssyyyyhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh-
ssyyyyyyhhhhhhhhhhhhhhhhhddddddddddddddddddddddddddddddhddhhhhhddhhhhhhhhhhhhhyyhhddy+/::+sysoooosssyysso+///::::-----:/ossso+syyyyyyyyyhhhhhhysyyhhyyysssosssssssssssssoososh+.+yohhyo///ohy+++oso+////////:://:///////+o+///+o//:/.-+:....-::::--::-.-..---.--..-:+sso++/////:///////++/+++++/////////////////////////://///::::///////:::////++++++oossososoossssssoo/-.`.-::///+osyo+:::::::://///++////+++++++++oossyyyyyhdNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNd-
::::::::::::////////////+++++ooooosssssssyyyyyyyyyyyhhhhhhhhhhhdddddddddhhhhhhhhhhddy+/:::+ssoooooosyyso++//::::----://osso+:-ohyhhhyhhyyhhhhhhyyyhhysssssoosssssssssssooosooyhhy+/ohdyo//+yhssso++/+oo+o+//////+ooosooss+o//::/::/:.`..-+:--.``-::::-.---:-------...-:/+//////////://///+++++///////:::::////:::::/://////:::::::////////////+////://++o+++ooooooooo++o+:::///++oosyso:::::::::::////++++//++++++o++oossyyyyhhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNh-
---------------------...-------------::::::::::::::::::///////+++++ooshhhhhhhhhhyhdds+/:://ossoooossyys+///:::::::://+ooo+/:-:shhhhhyyhhyyhhhhhhhhyyyssssssssooossssossooooooosyo+++ohdyo++oo+/+++oooo/:/oso+ssoossso+/++//:--://---.````.`.-...---:--::-:--:---:---:::-::////://////////++//+/////////:::::::::::::://:://::::::://////////++++++/////+++++++oooooooooooo+++oossssso+////::::::::///++++++/++++++oooooossyyyhdNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNh-
---------------...........--------------------...-.....--------------/oyhhhhyhhhhhdds+/::///+ssoosyyss+//-.-.``./+++++oo+:-../yyyyhyyyyyyyyyyhyyhhyssssssssssoossssooooooos++oo+++++++syho+++//oooooyysoss+/++/::::++/:--::-/:-:/.-:.`````.....--...-::::::---:::---:::://///////////////////////////:/:::::-::::::::::////://////+/////////+++++++/////+++o++++++oooooosyssssyyyssoo++////::::::::////+++++++++++ooooossyhhhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNh-
---::-----------...........----------------------..------------------/oyhhhhyhhhhhdhs+/////:/osssssso+//:`    ```/so+o++/-.`-+yyyyyyyyyyhyyyyssyyyyssssssssssoooooooooooooo+ooo+++o+o++ohhooo++yyyyyhyo+/::.-+:-:::+//o+//..-.-++:::-...``...``..-:://:--::::--::-:-----::://///:://++//////////++///::::::///::///://////://///////////////+++++++++///+++++++++++ooooosyyhyyyyssssooo++//:::::::://///++++++++++oooooosshhyymNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNh-
---:-------------....------------------------------------------------/shhhhhhhhhhddhs+/////://+ossso+/::-`   `..`-+++++/:.`.-+yyhhyyyyyyhhyssssyysssssssssoossssoosoooooo++oooo+o++++//oyhhhhhhhhyyyyhys/-.-:/:-::/+//so////.`.---...............---:///:--:::::--:::::::::::://///////////////////////:::::/::::::://////::://////:/+///////////+++////+++++++++++oooossssyyyyyyssssooo++////::::///////++++++++oooooossyhhyydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNd-
-:::------------------------------------------:----------------------/shhhhhhhhhhddho+////////++osss/.`..```-/--::/++//:...-:+yhhyyyyyyyyyyyyyyysssysssssoooooooooooooo+o++ooo+++++++++ooo++shdhhyysss//syss+::/::/:./+:-://-:/-````.``....`..--------:::-------::::/:::::::/:://///:://////:////::///://::://:/:://:/:::/::::::/++/++///////////++++//+/++++oo+++oooosssssssyyssssyssoooo+////////////+++++/++++++osoosyyhhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNd-
::::-----::::::::--:------------------------::::::-:::---------------/shdhhhhhhhhddho+/////////++ooo:.```  .:/----.:/::-...-:+syyyysyyyyyssyyysyssssossssssssossssooooo+ooooo++o+oso++++++++oydhysssso////+++++/:--..::::-:///:.-/.....`..--.------:---.---------:::::::::::::::////::::::/://///::::/://:::::::::::::///:::///::/+o+///+o+//++++///++/+++oo++oo++ooooosoossssyyyyyysssoooo++////////++++++++++++++ossossyhhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNd-
///::::::::::::::::::::-----..--------------::///:::::::------------:+yhdhhhhhhhhddhs+////////+//+oo:` ```.--..`  `:+:--..-:/+syyyhyyhyssyyyyyyyssyssssssssoosssooooooo++oo+++ossso//++//+++ooyhhssysso--++--++oso://:--..:/:.``.----.`.::-.----------...----::::--:::::::::::::///:/::::////////::::/::::/+////:/+/:///+///:::///+o+++//++oo++++//+ooo+ooooooooo++oooosssssssssyyyysssooooo++////////++++++++++++oosoosyyhhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNd-
////////////////:::---------.---------------::////://::::-----------:+yhdhhhhhhhhddho+////////////+o/.``-odh+-   -/+/:----:/+osyyyhyyyyyyyyyyysssssssssssssssssssssssso+ooo++ossso+////+///+//+syhhy+:-./+++//:/+os+oso:..`.``:-`.-/:.....--------::------:::::::::::-::::::::://::::::/:::::::::://///:::/oo+o+:+o+/++++++++o+++oooosssoo+oso+++++++ossoooosssoooo+++oooosssssyyysyyyssooooo+++///////+++++++++ooooooosyhhhdmNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNh-
/////+++//////:::---------------------------::::::////:::-----------:oyhhhhhhhhhhddho+/+//////++//+/.````.:/++.`.oy+::--::/+syysyyhhhysyyyyyyysssssssyyyyyyyyyysssyyyyys++oooss+o+/++++/:/+++++ooyyssooos:.--///+o/:::+o+++-.:-..-::/-..-----:::::::::::-----:::--::::::::::::///::::::::::/:/o+//+++///osooo++::///++o++oo++oooo+ooo+oo+//+ossso++++ooooo+oossyhyssooooooossssyyysyyyssssooooo++++///++++++++++ooooosssyhdddmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNh-
///////////////::--------------------------:::::::::::--------------:oyhdhhhhhhhhddho+/+//////+/++++-`  ---:/:../+/::::://+sddyyhhhyhyyyyyyyyyyssssssssyyyyyyssssoosysso/+sssso++/++o+////++++++oyhyosyooos+-..:+/::/+//:::.//-::.://..-:----:--:::-:::::::--::::::-:----:::::::--:/://+//+o//o+:/+ss/::+oo+/++///++oo++++oooooooooooooosooooosssssooo++oo+//ososyssosssosssssssyyyyyyyssssssooooo++/+++++++++ooooooossyyyhddmNNmmmmmmNNNNmmNmmmmmmNNNNNNNNNNNNmNNmmmmmmNNNNNNmNNNNNNNMMMMMMMMMMMMMMMMMMMNNNNNNNNNh-
///////////////::----:::-----------------::::::::///:---------------/ohddhhhhhhhhddys++++++++++/+//+:`  ```.--/++:::::/+ooosmmhyhhhhhhhyyyyyyyysssyyssssssyysssossoooooo+osss++o++oo///////+++///oyysoso++oooo+//::/:-++-..-///:-.-//-.-----:::::---:::-:::-::/::::::::::--:::/:///:+oo/::oy+:oo/+oo/-/++/+++++/++++++++++++ooooooooooooo++++++oooosssoooooooossssyyyysosyhyyyyhhyyyyyyyyysssssooo+++++++oo+++++oooosssyhhhhdmmmmmmmmmmNNNNmmmmmmmmmmNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmNNMMMMMMMMMMMMMMMMMMMNNNNNNNNNh-
//+/////////////:--::::-----------------::::::::////::--------------/ohdhhhhhhhhhddys+++++++++++++++:..-////////////+++/:/ymmhhhhhhhyyhyyyyyyyyyssssssssssyhyysssso++oooossso+ossoooo+////////++++oyhyyoo////oyoso::-.::..-:--::-.-:/-`-----::-:::::::::::--:::--:/:-::+/-:/o+:-/+++yho-:/s+::+/////:::///:/:://++/+///+++oo+//++++//:://://:://++/+ossssssoooooosyyyyysyyyyhhyhdhyyysyyyyssssoooo++oo++ooooo++oooossssyhhhdmmmmmmmmmmmmmNmmddmmmmmmmNNNNNNNNNmmmmmmmmmmdmmddmmmmmmmNNMMMMMMMMMMMMMMMMMMNNNNNNNNNNh-
////+++++///////:::::------------------:::////://++/::--------------/shddhhhhhdhdddyo++++++++++++++++oo+++shhhysssyhhhhyshddhyyhhhhhhhhyyyyhyyysssssssossyyhhyssssso+ooosssooosyys++++/////////++++ohdyyoooo+o+///:/o+:..-:/-----:-:/-.--------::://:-:::/::/:---::-:::::::+:--:osyso+:--://++:-::::::::://://////:::::/+/::::------------::-://///++++++ooooo++++oosyyyyyssyyyyddhhhyyyyyysssooooooooo++ooo+ooooooosyyyhhhdmmmmmmmmmmmmdmmddmmmmmmmNNNNNNNNNNNmmmmmmmmddmmmmmmmmmmmNNMMMMMMMMMMMMMMMMMMNNNNNNNNNNd-
::://++++++/////::::::-----------------::/++//://++/::-------------:/shddhhdhhdhdddyo+++++++++++++++++++++odmNNmmdddddhhhyhhhhyhhhhhhhhhyyyyyyyyssoossyyyhhhyyyyysooooosyyyssssso+/++//////::++++++/ohdyso+ooo+/++//++shs/-``.---..:/:..---::/:::::::::-::/:--::----::::-+o:::-:syos+::-.-:--:-:::://::///:///--.................--..-------::::///////++++++++++/+++oosyyyssssyhdddddhyyyyysssssoooooooooo++oooossssyyhhhdmmmmmmdmmmdmmmdmmmmmmmmNNNNNNNNNNNNNNmmmmmmmmmmmNNNNNNmmmNMMMMMMMMMMMMMMMMMNNNNNNNNNNNMd-
///+oooo++o+++//:::/:::----------------:/++++///+++/::-------------:/shddhhddddhdddyo++++o+++++ooo++++++o+ohmNmddddddhhyhhhhyyyhdhhhhyhyyyyyyyyysssssossyhhhyyysssoosssssysoooso+//+++/+//+////++o+++syyssyo/+//////+-:o+/++/:.`..-:+:..---:/:::::::-::::/::::--:///:-//+/::/+/:-:-:::----:::::///:::::::-.````````.......--...----..--------:///::://///+ooo+oso++/++++osssssosyyhdddmdhyyysssssssooooooooooooooosssyyyhhdmmmmmdddmmmmmmmmmmmmmmmNNNMNNNNNNNNNNmmmmmmmmmmNNNNNNNNmmNMMMMMMMMMMMMMMMMMMNNNNNNNNNNMd-
+++oooo++oooo++/::://::-------:------::::///////++//::-------------:+shddhhdddhhdddyo++oo++++++ooooooooooooyhdmmdddddhhhhhhyyssyhhhhhhhhyyyyyyssssyysosssyhysssysossysssoooo+ooso+++++//////+++//++++++yhooss/oy+-..-./+::::/++///::/-----::::::::::::-://-----::-..-://--:+o/:-..-------::::/:::::.``   ```.....-......---....-------:----.-:/:-::---::::/++ooo++++++/::/++ooosssyyhhdmddhyssssssssoooooooooooossssyyyyhdmmmmdmmddddddddmmmmmmmmmNNMNNNmmmNNNNNmmmmmNNNNNNNNNNNNNmmNMMMMMMMMMMMMMMMMMNNNNNNNNNNNNd-
ooossoo++++ooo+/:::///::-----::-------::://////////:::-------------:+yhddhhhddhdddhyooooo++ooooooooooooooooooydmmmdddhhhhhhhhsyyhhhhhhhhhyyyysssssyysooosyyyyssssosssooosso++oooo++///+++/////++++++++++hhosysssyso+/o+-.-+/.-//:+/-:-..-::-:/:::::--::::---:-::---.---.-/o/.`......--..:::--..```````.-----:::-----...--.....--..--.-:--:--://:::--..--:://+ooo++++++///::://+ooosyyyhdhddhysssssssssooooooo+oossssyyyhddmmdddmmddddddddmmmmmNmmmmNNNNNNmNNNNNNmmmmNNNmmmNNNNNNNNmmNMMMMMMMMMMMMMMMMNNNNNNNNNNNNNd-
sssssoo++++ooo+/::::://:::---::::::::--:://///////:::-::-----------:oyddddddddhddmhyoooooo+oooooooooooooooooohddddddhhhhyyyyyyyyhhhyhhhhhyyyyyssssysssossssssssssooosso+osoooooooo+//++++++++///++++++o++ydhhyoo+++syso+::-..:/--//:/:--::::::////::::////--:-.------......``........--::-.......:://///:///:::--.--..-.------...--:-----:---::-::-...--::/++ooooo++/++////::::/++osyyyhhdmddhssssssssssooooooosssssyyhhddmmmmddmmddmmmmmmmmmmmNNmmmNNNNNNNNNNNNmmmNNNNNmNNNNNNNNmmmNMMMMMMMMMMMMMMMMNNNNNNNNNNNNNd-
osssso++//+oo++/::--:::::::--:::::::::-:::::::///:::::::--------:--:oyddddddddhddmhysoooooooooooooooooooooooshdmddddhhhyyhhhyyyyhhhhhhhhyyyyyyysssyyssssssyyysoossssssoossooo++osoooo+++++/+++/+++++++ooo/odyhyso++ss//+/++/+/---:-:+/---:-:::///::::://::/+/-::://-...```````.....--:-.---://++++++++///++/+/://:-::------:-...---.-.-:::::::::-----...-:///+oso+///++//////:://+++oyyyhdddddhssssssyysossooooosssyyyhddmmmmmdddmmmmmmNNmmmmmmNNNmNNNNNNNNNNNNNNNmmmNNNNNNNNNNNmmmmNMMMMMMMMMMMMMMMNNNNNNNNNNNNNNd-
+oossoo+++oo+++//::::::::---:::::::::---::///++//::::::::--:--:::::/ohddddddddddddhysoooooooooooooooooooooosyhdddddhhhhyyhhhhyyyhhhhhhhhyyyyyyyyyyysssssssyyysyyyyssosysssooo+++ooooo+//+++++/++++++++++o++yhhssoosso//+/.-++:::----/:----::::://://::/:---...-::-..-.`.--.`.......---:://+oooooooooooooooooo+:-::/::::/:-:::---::-----:-::/:--------...-/++++o+////+++////////+++++osyyyyyyddhyss+osyyysssooosossyyyhhdmmmdmmmdmmmmmmNNNmmmNmmNNNNNNNNNNNNNNNMMMNNmmmmNmNNNNNNNNmmmNMMMMMMMMMMMMMMMNNNNNNNNNNNNNNd-
+++ossssssso+/::://::::::-:::::::::::::-::/+ooo+/:::::::::::::://::/shddddddddddmdhysoooooooooossooooosssooshdmmdddhhhhyyhhhhyyyhhhhhhhhhhyyyyyyyysssssssssssssosyysosssossoooo+/++++++++++++++++++++++++/+oshdyyssos++/-./+/---:---//--:-:::::////-:/::/+:``...``..```...````.-..-:/+o++ooooosooossssssoooooo++++/:///:-:///::://:--::::///:-:::::-....:/++++o+/:/+++/+++/////oo+++ossyyssyhhhhyssssyyyysssoooosyyyhhddmmmmmmmmmmNNNNmNNNNNmmmmNNNNNNNNNNNNNMNNNNNNNmmmmmmNNNNNNmmmNMMMMMMMMMMMMMMMNNNNNNNNNNNNNNd-
////+osyyhys+::::::::-:::::::::::::::::-::+oosso/:::::::::::////:::/shddhhhdddddmmhysooossoosoossooooossssoyhdmdddhhdhyyyhyyyysyhhhhhhhhhhyyyyyyyyyssssssssssssosssssssyssooo++o++++++++++++/+++++++++/+ooo++ydhssooy+:-.:+:---:----//-.::::/:::/:::::--::..`...```````..```..-::/ooooooooooossssyyssssoooooo++++/+///:::::::::::::://:::///////::-..--:/++++++//:/+//+++++/:/osoo+++ossyssyhhhy/-/syyysyyssoooosyyyhhddmNNmmmmmmNNNNNmNNNNmmmmmNNNNNNNNNNNNNNNNNNMMNmddmmNNNNNNNmmmNMMMMMMMMMMMMMMMNNNNNNNNNNNNNNd-
/:://+oosyyo/::::-::--::::::///+//::::--::/+ooo+/::::://///+++//:-:/shddhhhdddddmmhysoosssssoosssssssssssssydddddhhhdhyyyhhhyysyyhhhyhhyyyyyyyyyyyysssssssssssoosssoosyysooooooooooooo++++++//+o+/++++++++++++syyyss+/oosys+:.``.--:+/-.::///:::///::::::-....``````````````-/+osssssoossosssssssssooooooooo+++++///////////++//:://:::://///+///:--:://++o+++////+//+++++/:-+soooo++osyyysyhhyhhyossssyyyssosssyyyyhdddmmNNmmmNNNNNmNNNNNNmmmmNNNNNNNNNNNNNNNNNNNNNNmmmmmNNmmNNNmmNNMMMMMMMMMMMMMMNNNNNNNNNNNNNNNd-
/://///++o+/::::::::::::::::/++ooo+/::::::///////////////++++++/:::/yhddddddddddmmhyssssssssssssssssssssssshddddddhhhhyyyhhyyssyyyyhhyyyyyyyyyyyyyysyyssssyyssoooooo+oysooo+++oosyysso++++///+++++//++/++//+ooosyhhy+/+yyooss+//:::://--::::::-://::::---..---.`...`..```.:+osso+++oo+o+++++++++//+++ooooosoooooso++ooo+++ooooooooooooooo++////:::::::///+++++///+++++++o/:/+soooosooosssssyyyyhhdysosyyysssoosyyyyhhddmmNNmmmmmNNNNNNNNNNmmmmNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmNNMMMMMMMMMMMMMMNNNNNNNNNNNNNNNd-
+++oo++++++//////:::::::::::/++oooo++///////++++++oo+++//++++o++//:+yhddddddddddmmhyssssssssssssssssssssssyddmmddddhhyyyhhyyssyyyyyyyyyyyyyhyyyyyssssyysssyyssoosoooossooooo+ossssso+oooo++++++o+++++++++++//+oosyhyooyyo+///-:+//:/+/.-:://::::////::----..--...````.``-/+oyys/::::-----://:/+++++ssso/////:::/::---------.---::::::///+++o+++++++/////++/+///////++++++++oooosssssosyyyyssssooossyyyhyyysssssyyyhhdmmmmmNmmmmmmNNNNNNNNmmmmNNNNNNNNNNNmNNMNNNNNNNNNNNmmmmdddmmmmmNMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNd-
ooooooooo++++++++////:::::::://++oooo++++++++++oo++/////////++o++//+yhdddddddddmmdhysssssssssssssssssssssshdmmddddhhyyhhhyyyysyyyyyyyyyyyyyyyssyysysssyyssssssooosssssooooosssyyoo++o+ossoo+++oo+/+++++++++//+o+osyhyyhsoo+/-`-:-:::+/-.::/::///::::::-:----..``.`...`.-/+ossyyso/:..----:::::///////+o++/+o++++++oo+//::---...........-------:///+++osssoooo++/////////+++oooosyyyssssyyysooso++ooyyhhhyssssyyyhhhhdmmmmmmNNNNNmmmmmNNNNmmmNNNNNNNNNNNmmNNMNNNNNNNNNNNmmmdddddmmmmNNMMMMMMMMMMMMMMNNNNNNNNNNNNNNNd-
ssssssssssooooooooo++/:::::::::/+oooooooo++++o+++++////:::::::///::+yddddddddddmmdhysssssssooooo++++/////+ymmdddhhhhhhhhyssyyyyyyyyyyyyyyyyyyyyysssssssssssssssooooossoooosssssso+++++osso++++++++++++oooo++++++o+oddysys/--.:+/-://o+:.::::::--/:::-::--:::--...-.`...-:::+oosyss+:-:/:-:/:::/:://///+//://+++///++++oooo+o+++//:---.....--........---:/+sssso+++++++++ooo+oosyyyysssyysso+oo+::ossyhhhyssyyyhhyhhddmmmmmmNNNNmmmNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmddmmmmNMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNd-
sssossssssooooooooooo+/::::::://++oooo+++++++++++////////::::::::::+ydddddddddddddysooooo+//::::--::-----:smmdddhhhhhhyyyyyyyyyyyyyyyyyyyysyyyysssssssosssssssoooooooooooosyssyso++++/+sso++++++++o++ooo++++++++oooshhyyyso+oso/:::+s+-.-::::/:://:::/:-::---...-...--.--..-:+osssoo+/:-://:::////////////////++++/+////////++oosssoo+/:--------....------/osyysooo+++++++oosssyyyyssssssssooo+++syyyhhhysyyyhhhyhdmmmmmmNNNNNNNmmmNNNNNNNmmNNNNNNmmmNNNNNNNNNNNNNNNNNNNNmmdddddmmmNMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNd-
sssssoosoooooossssooo++//:::::/++ooooooooo++///////+/////:::::::-::+hdddddhdhhysso+///::------------..---+hmdddhhhhhhyyyyhhyyyysyhyyyysssyysyyyssssssssssoosssosssooooooossyyyys+++++/+oo++++++o+ooo++++++++++o++oo+shhysoooso++++:/so:-:::::::::/:-:/:-::---..::-.::..--.--:/+ossssooo/////:://///////////////++////////////////+oosyysooo++//::-----::/+oss/::+so+//+oossssyyysssossoooosoo++osyyyhhhhyyyyyyhhhhddddmmNNNmmmmmNNNNNNNNNmmmNNNNNmmmmNNMNNNNNNNNNNNNNNNNNNmmdmmdmmmNMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNd-
ooosoo+++ooosssssso++++//:::://+ossooossso+///++++++//////::::::::/ohddhyso+//:::---::---------:-------.-sdddhdhhhhhyyyyyyyssyssyyyyyyssssssssssyyyssssssossssssssoosssoosyyyssso+o++oooooo+++++++oo+++++oo+++++++oo+oyhyysoo+//////so:::::://::::/::/:::::--..:////:/--:-:-:--:/++ooo+//:///::/:////////:///:::::::///::--:///////+++oossssyhyyyysso+oossyysysoossooosssyy++ossooooo+++ooosso+oosyyhhhhysyyyhhdddmmdddmNNNNmmmmNNNNNNNNNmmNNNNNNmddmNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmNMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNd-
oossoo++++oossssoo+//////:::://++ooooooooo++//+++o++///////:::::::/+oo+/:---.--.-----------------::-----/hmddhdhhhhyyyyyhyyssyyyyyyyyyyyyssssssssssssysssoossssooossyyssssyyysssoooosssssysso+++++oo++oo+oo+++++ooooo+oyhhyso+//////s+--::::////////:::::::/::::///::///-..-:-://////+oo++//::::::://////+/::::---:::::::::::::::////++/++oooooossssssoooooo++/++++osssssyysooo+++/---:oosssso+ooosyyhhyyyyyhdhhdmmmmmmmNNNNNmmmNNNNmmNNNNNNNNNNNmmmmNNNNNNNNNNNNmmNNNNNNNNNmmmmmmmNMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNd-
oosso++++++ooosso++/////::::://+++oo++//+++/////++++/:/+++///::::----....................--------:------ohdddhhhhhyyyhhhhyyyyyyhysyyyysssssssyysssssyssssssssssssoosssyyyssyyyyoooosyysooosyso++oooooooo+ooooo+++oooo+ooyhysoo+////+yo:-////::::///:///::::-:://///////::::--:----://::::///::/:--::::::://---:--:///:...::::::::::://///+++ooooooo+////+++++++++++++osyyyyyyyso+/++//++osssssossshdddhyyyhhddhhdmmmmmmNNNNNNNmmNNmmmmNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmNMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNd-
+oooo+++//++++++ooo+//:::::::/+++ooo+///+++///://++////++/:---...........`........-.....---------::----+hddddhhhhhyyyhhhyyyyyyyyyyyyyyyyyysssssssysssssssssssoossosyysssysssyyysooosyyso+ooso+++oooossoo++oooo++oo+ooooooyhso+++//++os+--://///:::::://///::::://///++/:::/:::--::::::--::/::----:----.--...:....-:----..--..``-:::::/://///+++oo++++/://++o+++++/+ooooosssoosyysoos+/+osyssyyssyhddhhhhhhhhhdddmmmmmmNNNNmNNNmNNmmmmNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNmmmmmmmNMMMMMMMMMMMMMNNNNNNNNNNNNNNNNMd-
oossoooo+++o+++++++/:::::::::////+++//::/+++//////:::----...````....``````````..............----::----:ohddddhhyyhhhhhhyyysssysssyyyyyyyysssssossssssyssssoooooosssssyssooossyyyssosyssso+oss+++oooosssoo+o++++oooooooooooyhyoo+//++oo+:::://////::://:::/:/+/:::///////:::/+::::::::::::--:::-::--:::--:..-:.....``..`.-----...----::::://////++++++/:////++oo++//+so++ooso++osyysso++osyyssyyyyhhhhyhhhhhdddddmmmmmNNNNNmmmNNNNmmmmNNNNNNNNNNNNNNNNNNNNNNNmmNNNNmmmmNmmmmmmmmmmmmNMMMMMMMMMMMMMNNNNNNNNNNNNNNNNMd-
sssssssooosooo+////:::::::::::/::///::////++++//:---........```````````````````..........-.------:::--:shdddhhhhhhhhyyyysssyyyyyyyyyysyyyssyyyyssssssssssssssssssssssssoososssyyysoosyyso+ossooo+ooossoo++++oooo++oooo++oosyhhso+/++o+:-://://://::://///++///://///////-::://::/::::--::-....-:--::.-:::..::.``--` `` ``...-.-------:---:::::::///++/::////++++++++ooo++++++++osyysooosyhhysyyyhhhhhhhhhhddhhdmmmmdmmNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNmmmmmmmmmmmNMMMMMMMMMMMMMNNNNNNNNNNNNNNNNMh-
ssyyyyssosssso//::::::::::::::::::://///////::--............````````````````....--....-...----::::::--/yhddhhhhhhhhyyyysyyyyyyyyyyyyyyyyyyyyssssssssssssssssossssoossssssssoosssyysosyyssosoooo+++ooo+ooo+++o+o+oo+++oooooooohdhs/++so//:////+////////::/++/://////////:::::///://////::/:----.-----..-.---:-..::-....````.`.-.``.--.---.-----:::::////::://///+////://+++//++++oyhysssyyhhysyyyyhhhhhhhhhhdddmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmdmmmmmmmmNNMMMMMMMMMMMMNNNNNNNNNNNNNNNNNd-
ssyhhhyssyyys+//:::::::::::::::://++oo/:::-----.....`.``...`````````````.`.....---.........-----::::::+yhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyssssyssssssssssoossssssssssssssssoosssyyyssyyo/osoosoooooooo+/+ooooo++oooooooooo++sddhs++ys/::/::::/++/////////////+////////:::://///://::///++//+/.......---.-:-:::::---.`--.`````.```........------:::::::--::-::://://::::///+++++osyyssyhhhyyyyyhhhhhhhhddddddmNNNmmmmmdmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmdddmdmNNMMMMMMMMMMMMNNNNNNNNNNNNNNNNNd-
sssyyyyyyyyyso+//:::::::::::::////////:----............``......`..`````......---------...------:::::-/shhhhhhyyyhyyhyyyyyyyyhhyyyhhyyyyyyyyyyysyyssssssssoooossssssssooossoooooosssssssssssssoooosooossssooooooo++++++oo+o+++oshdyysso+::://:///::///////////////++//////////:://:///::/+////+//:::-...-`.-.--://--::.-:-.--.``.``..``.-..-------:::--:-----:--:::://:::///+++++ossoooyhdhhhyyyhhhhhhddddddmNNNMNNNmmmddmmmmmmdmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmdhdmNMMMMMMMMMMMMNNNNNNNNNNNNNNNNNd-
hysssyyysooooo+//::::::::::::::::---...--.....................``..````.....-.--...........-----::::--/yhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyssyyyysssssssssssssssssssssssssssyysssooosysssoosoooooossoooooooooooooooooooooo++o++ooooydhyys+//::::+/::/:::///++///////////////::://:-::::////++////////:::/:-.....``.:-.-:---------:---.`.---..------::::------------:://:://///+++ooosso+ohdhhhhhhhhhhhhhddddddmNNNMNNNNNmmmmmmmmmdmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmdddhhdNMMMMMMMMMMMMNNNNNNNNNNNNNNNNNd-
yyysso+/:--:::::::::::::::::::-----...............................```.....-...........-...-----::::-:+yhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyysyso+syyssssssssssssoosssssssoossssssooosoosooooooosssoosoossoooooso++osooo+osso++o+++shhhyo//++///+/:///://///++///////////////:///////::///+//////////////:-::-.........--..-----::::---:-------.--:::-::::----:::::///://+++++++oooooo+shddhhhyhhhhhhhddddddmNNNNNMMMNNNmmmmmmdmmmmNNNNNNNNNNNNNNNNNMMMNNNNNNNNNNNNNmmmmNNNNNmNmmdhyhdNMMMMMMMMMMMMNNNNNNNNNNNNNNNNNd-
oo+::-...................-------...................``.......`...```....---............-.-----::::::-:+yhhhhhhhhhyyyyyyyyyyyyhyyysssyyyyyysssysssyyyssssssssssssssssssssssssoosssssosossoossssssssoooooossooooso++oosooooooooo+++++oshhs++++//++//+//+++/////////////+////////:::////////////////////////////::---...`...```...---::-::::------::::::::::--:::///://///++++/++oooo++oshdhdhhhyhhhhhhhdmdddmNNNNNNMMMNNNNmmmmdmmmmmmmNNNNNNNNNNNNNNMMMNNNNNNNNNNNNNNmmmmNNNNNNNNmdhhhdNMMMMMMMMMMMMNNNNNNNNNNNNNNNNNd-
/:-..........```````````.....-.````..`````..`..```````````````````..---...............-----::::::::-:+yyyhyyyyhhhhyyyyyyyyyyyysssyyyyyyyysssssyyysssssyssssssssssssssssssssoossssssoossoooosysssyssosssssooooooooooo+oooooo+ooo+++++oooo++++++//////////////:///:////////////::://////////////////////////////////:::::-----.......----:::::::::::::::/::::///////////++++++++++++oshdhhddhhhhhhhhhdmmdmNNNMMMNNNMMMMNNNmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMNNNNNmNNNNNNNNNNmmmdyydNMMMMMMMMMMMMNNNNNNNNNNNNNNNNMd-
-.............````````...`...-.```````````........`````````````..-----...........---...----:::::::--:oyyyhhyyhhhyyyyyyyyyyyssssssyyysssssssssssssssssyyysssoosssssssssssssssssssoosoooooosossssssssoooooosssoosoooo+++o+oooooooooo++ooo++////+++//++//////////:://++/////////:///:///////++////+++++++//////+++++++//+//////:::--.-----:-:::::////:://::::////://////////++++//++oyhdhhhhhhhhhhhhhdddmmNNNNNNNNMNNNNMNNNNmmmdmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmdddddyoshNNMMMMMMMMMMNNNNNNNNNNNNNNNNNMd-
..........---.```````..```....``````````````....```````````....--.................--------::::::----:oyyyyyyyhyyyyyyyyyyysssyyyssssssssssssssssyyssssysyyssoosssssssssssssssoossooossooossssooossssssooooossosssssoooooooossoooo+++++++++/+++++///++++//////::////+//////////::///::////////++++++++++++++++++++++///+++++++///////////::::::///://///::////:/::::/:///////++++osyhdhyyhhhhhhhhhhhhdmNNNMNNNMMMMMMMNNNMMNNmmmmmmmmNNmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdhyyysooshNMMMMMMMMMMMNNNNNNNNNNNNNNNNNMd-
......-----::-`````...```...``````````````````````````````..-...............-.....--:----:///:------/syhyyyyyyyyyyyyyyysssyyyyssssssssssssssssssyysssssssssyssooosssssosssssssssssooooooso+++ossssssoooosssssssssoossooooooooooooooo+++++o++++//////////////::://://///////////////:::///:://++++++++o+ooooo+++oo+++oo+oooooooooooooo+++++////////////:////::::::::://///++oooosyyhhyyyyhhhhhhhdddddmNNMNNMMMMMMMMMNNNNNMNNmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNmdhysyyssydNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNd-
.........-::/:.`....````...```````````````````````````............................-::::::::/:--..---:syyyyyyyyyyyyyyyyyssyysssssssoooooooossoossssssssssyyysssssssssssssssssssssssssssoossooooooossoooossosssssossooooosssosooooso+++++++++++++/////://///////////:::::://///:://////////:///+///+++++++++++++ooooo++oooosooooooossssooooo++++o+++++++++++///////////++oooosoosyyyyhhhhhhhhhhhhddmmNNMMMMMMMMMMMMMMMNNNNNNNmmmmNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmddddhyhhysydNNMMMMMMMMMMNNNNNNNNNNNNNNNNNNd-
.......----:/+/-...`````...````````````````````````..---......................-.---:::::::::----...-/syyyyyyyyyyyyyyyssssyssssssoooooosssssoosssssyssysyyyysssssssssssssssssssysssssssssoosssoooooooooooooossoooooooooossoooosssooo+++++/+o+/++///////+o+/++//+///:////:::////::::////:///::////:::::::///++++++ooo++ooooooooosoooo+o+//oo++ooo++ooooooo++++++++++++ooooooosssyyyhyyyyhhhhyhhddddmNNMMMMMMMNMMMMNNNNNNNNNNNNmmmmmmmNNNNmmmNNNNNNNNNNNNNNNNNmmmmmmmNmmmmdhhhyyso+//ohNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNd-
...----::-:/+o+:..`````..```````````````````````..---......................--------::/:::::--.-...--+syyyyyyyyyyyyyyysyyssssssssooosossssssoooosssssssssssyyssssyyysssssssssssssyssssssssossssssooooooosoossossoooooooooooooossoooo++++++oo++++++/////////++///++//////::/:////:::/://///:::/:////:::::/++////////+++++oooso++o+++++++++oo+++ooooso++++ooo++++++++++ooooosyyyyyyyhyyyyhhyyyhhddddmNNNNNMMMNNNMMMMMMNNNNNNNNNNNmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNmmddhyso+::-:+hNMMMMMMMMMMMNNNNNNNNNNNNNNNNNMd-
...--::::::/os/-.`````.```````````````````````..--.........................-----:::///::::---....--:+syyyyyyyyyyyyysyyyssssssssoossssooosssooooossssssyysssssssssssssssssssssssssssssssyssssssssossooooosssossssssooooossooossoooooooo++oo+//+++///////////////////////:/::::::::::::::://:::::::::::::::://////////+++oooo++++++++++++o+so++ooossoo+oossoooooooooooosssssyyyyyyyyyhyyyhhhdddddmmmNNNmNNMMNNMMMMMMMMMNNMMNMMMNNmmmmmmmmNNNNNNNNNNNNNNNNmNNNNNNNmmmmmmmmddhyso/::--+hNNMMMMMMMMMMNNNNNNNNNNNNNNNNNMd-
....--:////+os+-`````.``````````````````````..----.........................----:/+++/::----......--:+syyyyyyyyyyyyysyysssssssssssssossssssoooooosoossssssyssssssssssssyysssyyyssssssssssssssssssssssossssssssssssossoosooooossssssoooooo+o++oo+/////:://////+//::///////////::::::::/:::::::-:--::-::-:::::://////////++//++o+++oooooooooooooooooooooossssssosssssssssssssssyyyyyyyyyyhhhhhddmmmmNmmmmmNNNMMMMMMMMMMNNNNMMMNNNmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNmdhhyssoo+/::---+hNMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
..----:////+oso/-....````````````````````..----.....................--...----:////:------........---+yyyyyyyyyyyyyyyysssssssssssooooossssooooooossooossssyyssssssssssssysssssyysssssssssssssssyssssssssssssssssoooossoooosssssoosoooo++oooosooo++/////+//::::/::-:///::///:::::::::-:::::-------------.------::::://::////++++++ooooooosooossooossoossssssssssssssssssssssssyyyyyyyyyhhhhddmmmmNNNNNmmmmNNMNMMMMMMNNMMMMMMMNNNmmmmmmmmmmNNNNNNNNNNNNNNNNNNmmmmmmmmdhyso+//:::-----ohNMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
....--:::/+osyys+:.````````````````````.----..-.....................-....--:://:----.............--:oyysyyyyyyyyssyysssssssssssooooooossooooooooosssoooosssysssssssssssyssssssyyyssssssssssssssssssssssssssssssssoosssssssssssssssooo+++oooso+++++///++++/..-:::::::::/://::::::::::::::::::--:------........-----::::://////++/+++++oooooosssooosoosssssssysssssssssssssssyyyyyyyyyhhdhddmmNNNNNMNNNNmmmNNNMMNNNMMNNMMNNNMMNNNmmmmmmmmmmNNNNNNNNNNNNNNNNmmmmdddhhysoo+//::-----.-odNMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
``````..-:/++osso/::---......```````..-------........................-----:/::--.......--........--/syssyyyyysyyyyyssossooooooooooooooooo++oo+oooossssooosyyyssssssssssssssssyyyssysssssssssssssssssssssssosssssssssssssssooossssssooooo+ooso++++++/://++o/::/:-::::::::-:::::-:::----:--::::---.....`.`.......----::--::::///+++++ooo+++oooooosssoossssosssssssssoosssssssyyyyyyyyhhhhhdmmNNNNNNNMMNNmmmNNNNNNNNNNNMMMNNNMMNMMNmmmmdmmmNNNNNNNNNNNNNNNNNmmdddddhhysoo//::-----..:odNMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
``````` ````...----:://:/:://::----------....................--.....----://::----.-------.........:+ssyyyyyssyyssyyyssssssoooooooooooooooooooooooooossooossssssoossssssssssssysssssyyyssssyyssssyysssssssssossssssssssssssssoosssssooooooooooooo++//::/+//+/:::::-:::------:---------:------:---...`````````...--.---::::::::://+++++/++++++ooosssooosssssssossssoosssssssssyyyyyyyhhddmmmmNNNNNNNMMNNNmmmNNNNNNNNNNNMMMMMNNNNMNmmmmdmmmmNNNNNNNNNNNNmmmmmdmmmmmdhhyso+//:-----..:sdNMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
````  `        `````````...--------...........................-..-...-:::---------------.........-:+ssyyyyyyysssssyyssssssssssssssoooooooooooooooooossooossssooosssssossossssyssssssyyyssssssyyyyysssyyssssssssssssssssoosssoosssssooooooooooooo+++///://::::::-.--::--:--------------------.---....`````````.......-::::::::://///++/+++++oooooooooooooooooosssssssssssssssssyyyhhdddmmmmmmmNNNNNNNNNNmmmmmmmmmmmmNNNMMMNNNNNNNNmmmmmmmmNNNNNNNmNNmmmmmmmNNmdhyyso++++///:::--..:smMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNd-
```````     `     ```  ``````````````````.``.................-----.--::----------------..........-/oysyyyyyyyssssssssssssssssooooooooooooooooooooooooooooooooosoooossoooooossssssssssssyyssyyyyyyyssyyyysyyyssssssssyyssssssssoosoossooooossooooo++++////:://:.-:-.-----.---.------...----.....-.......`.````....--.-:::::::://///++///ooo++ooooooooooooooooooooossssssssssyyssyhhhddmmmmmmmmmmNNNMMNNNNmmmmmmmdmmmNNNMMNNNNNNNNNmmmmmmmmmmmNmmmmmmmmmmmNNmdhhyyso+//::::::::--..:ymNMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
`````````` ``` ```      ````````````````````````................------.....-----------..........--/oysyyyysyyyyysssssssssssssoooossossooooooossoooosooooooossoooooossooooooosssssssssysssssyyysyyyyyysyysssssssssssssyssyssssssssssooooossoooooo++//++//////+/::::----::-..----.......---....-.....````..``....--::---::--:::::////////+oo++oooooooooooooooooooooosssssssssyyyyhhyyhmNNNNmmmmddmmNNMMMNNmmmmmmmmmmNNMMMNNNNNNNNmmmmmmdmmmdmmmmmmmmmmmmmmmmmddmmmmdyo/::--------../ymNMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
``````````               `` ````````````````````......-.......-----..........---------..........--/osssyysssssssssssssyssssssoooosssssoooooooossooosoooooooosoooooooooosssoooosssosyyssssyyssyyssssyyyysyssssyyysssyssyyyssyysssoossooosssoso++o+++/++/:///////:--:::------..-:-...................```````.........--::--::::::::/://++o++++oooooooooooooo++ooo+oossssssoosyyyhhhyhdNNNNNmmmmmddmmNNNNNmmmmmmmmmmNNNNMNNNNNNNNmmmmmmmdmmmddmmmmmmdmmmmdddmmddmNNNms+//+////+/:-.-/hNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
``````````              ``` ````````````````................----................-----....``......-+ssssysssssyyysssssssssssssooooosoooooooooooosooossoooooo+oooooo++ooossssssssossosssssyyyyyyysssssyyyyyyysssyyyssssyyyssyssssssssssosssoooooooooo++++////::///::://:::-----..---.-...`.---.......`````....-.-.--.------:--::::::///++++++ooooooooooooooooooooooosssyssssyyyhhhddmNNNNmmmmmmmmmmmNNNNmmmmmmmmmmmNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddmmdddhhyo///::::::-...-/hNNMMMMMMMMMMNNNNNNNNNNNNNNNNNNNd-
`````````    `      `` ````````````````````...`...........-----..``......................````....-+sssssssyssssyysssssssssssssssoooooooosssooooooooooooooooo+oooooo++oooosssoooosssssoossyyyyyyyssssssyyyyyyssssyyyyyyysyyyyyysssssyssssssooossooooooo+++++///////:://:-.---.---:------.....`.........``....---::--::::--:/::::::://++++++oooooosssoooooooooooooossssssssyyyyhhhdmNNmmmmmmmmmmmNNNNNmmmmmmddddddmNNNNNmmmmmNNNmmmmmmmNNmmmNNNNmmNNmmdddhhmNmhso++++/:--....---..-+dNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
`````  `               ```````````````````..............----...````.`...................`````....:+syysyssyssssyyssssssssssssossoooossssooo+oooooooo+++o+++++oo++oso+++oooosoooooossssoosoosssyyssyyssssyyyyyysssyyyyyyssyyyyyyysssyysssssoooooo+oo+++o+++++/////////:::::::----:-----.--.--.`...`......-.----:/:--:::--::::://////++++++++++oooossoooooooooooooosooosssyyysyhdmNNNNmmmmNNNmmmmmmmmmmmmmmdmmmdddmmNNNmmddmmmmmmmmmmmNNmmmNNNNNNNNNmmddhyymNho//::::::--..--::--.-+dNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
```      `             ``````````````````...........--:---...````````.....`.............``````...-+syssssssssssssssssyssssssossooooooossooooooo+++++++++o++oo++ooooo++++ooossossooooosssoooooosssssssyssyyyyyyyyysssyyysssyssyysyysssssssooooooo+oo++ooooo++++///////::/::::::----:----:------..---.....---:-----::::::::::://////+++++++++++ooossssoosssoooooosssssssyyyyyhhdmNNNNNNNNNNNNmmmmmmmmmmmmmmdmmmmddmmmNmmdddmmmmmmmNNNNNNNNNNNNNmmmmdddhhysydmy+/::-----:----::::---omNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
````  ``  `    `    ` ```````````````````.........-:::-...`....`.````````..............``..``....-+yssssssssssssssssssssssoosssoooooooooo+ooo++/++++oooooo++++//++++++++oooosssso+++oossoosssooooosssssssyyyyyyyyyyyyyyyyyyssyysyysyyyyssssssssooooo+o+++o+++++++////:://::/::/:::/:--:::---------.---:::://:----::::::::////////++/::/+o+++oooossssooossssssssssssyyysyyhhhmNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNmmNNNNmmdddhhyysyhdho/::---------:::::---:omNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
   ```                ``````````````..........--:::--.....`...``....```..``.............`````....:oyysssssssssssssssssssssossssooooooo++++oo+//+++++ooo++o+++++++++++++++o++oooooooo++oossyyyysssoossssyssyyyyhyyyyyyyyyyyyyyysyyyysyyssssyysssssoo+++o+//ooo+++++++//://:://:::-.::--:-:/:----::---:--:::::---::///::/::://::///++//////++++oooooosoooooosssssssssssyyyhddmNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddhhhysssyso+/::----......-----..-:odNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNMd-
 ``````  `            ````````````.........-:::::-........```````````````..`..........````````..-:osyssssssssssssssssoossssssoooooo++o++oooo++++oo++ooo+++++++o++++++++++++/+ooooooooooosssyyysssssssossysyyyyyyhhyyyyyyyyyyyyyyyyyyyyssssssssysooooooo+oo+//++++++/++///////::/:::/:::-::::::::://:///::////+///++//////////////+/////++++++++ooooooossssyyssyyssyysosyhdmNMNNMNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmNmmmmmmmmmmdddhhyyysso+//::::----------------/ymNMMMMMMMMMMNNNNNNNNNNNNNNNNNNNMd-
````````  `        `  ``````````...`....-:/++/-......````````````````````...`.........`````````.-:osysssssssssssssssssoosooooooooo+++ooo++oo+/++++++o+++oo+++++++++o++++++++++oo+++oooosssoosssssssssssssoossyyyyyysyyyyyyyssyyyyyyyyyyysysssssssssoooossoo++ooooo++//++++++++///::////:://///////////++++++++////////+////////////++//++++++oooooooosssssssssyyyyyyyyyhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNmmmmddddddhhyyyyyyyyyysssssyhmNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNMd-
*/

/*int32_t free_gucci
 * INPUT: a process numer to free
 * OUTPUT: 0, success
 * FUNCTION: sets out global mask to free the process that has been halted
 */
int32_t free_gucci(uint8_t process){
	uint8_t mask = 0x01;
	mask <<= process;

	process_mask &= ~mask;

	return 0;
}

/*
 * unload_process
 *   DESCRIPTION: Called when to end certain process
 *   INPUTS: process - process number to end
 *			 parent_id - parent process
 *   OUTPUTS: none
 *   RETURN VALUE: 0 if success, -1 if failure
 *   SIDE EFFECTS: Unloads process
 */
int32_t unload_process(uint8_t process, int8_t parent_id) {


	if (parent_id < 0 || parent_id >= MAX_PROCESS || process >= MAX_PROCESS)
		return -1;

	// Frees process
	free_gucci(process);

	page_directory1[32] = (INIT_ADDR + (4 * MB) * parent_id) | PRESENT | PAGE_EXT | USER_ENABLE | RW_ENABLE;

	// Flush the TLB
	loadPageDirectory(page_directory1);

	return 0;
}
